### ISSUE TITLE
总结了几点，大神看下

### ISSUE THREAD

**Issue by cheapssr** [Ehco1996/django-sspanel#10]
01，关于服务器搭建时的nodeid
 "node_id": 1, # 改成你面板节点列表里的ID 注意 是ID 不是NODE_ID
按照这个规则的话，，增加节点，里面的节点id，，有啥用？？排序的？？
还有
如果面板删掉一条线路的话，新建线路，会跳过删掉的面板id。。
我测试站。。面板列表#2号删掉之后，新加节点从#3开始

02 我增加节点，选择的是协议和混淆，然而新用户注册以后，默认的还是orgin和plain，是不是我用的姿势不对

03如果免费用户，提升到了1级，用过一段时间，过期了
那么他已经知道了收费节点的地址。
他也有免费的流量，可以连上收费节点吗？

04定时任务命令，，重启需要重新运行吗？

05提交一个bug
重置端口点击之后，，
刷新页面，会一直换端口，刷新一次，修改一次。。

**Comment by Ehco1996** [comment]
01 node id 是用来统计流量之类用
02 协议和混淆设计的就是由用户自定义的，节点里的设置只是提供一个默认选项
03 过期用户节点会自动断开，不能使用
04 不需要
05 不是bug

**Comment by cheapssr** [comment]
02 新用户注册，他的默认协议和混淆，管理员能自定义吗，不想新用户默认orgin和plain
05 这个他只点了一次重置端口，然后页面刷新一次，就修改一次，不太合理吧。。就算再次更换，也要点一次重置端口啊。

**Comment by Ehco1996** [comment]
02 [fixhere](https://github.com/Ehco1996/django-sspanel/commit/a746a1d3efc1a2f8c577b6ea28275a0f5b194d91)
