### ISSUE TITLE
node_id问题

### ISSUE THREAD

**Issue by wangchencom** [Ehco1996/django-sspanel#100]
大佬 面板上的节点id就是后台的node_id吧 我这里跑起来之后给报一个
2018-04-18 02:48:50 WARNING  web_transfer.py:347 没有查询到满足要求的user，请检查自己的node_id!
user我是按照教程设置的 端口49999 域名/api/
simple_setting_product.py也改了管理员账号和端口
连不上我也不清楚是什么问题了 
求解答

**Comment by Ehco1996** [comment]
检查自己的 ss节点里的 userapiconfig.py 里的node_id 和面板里的node_id是否一致

还有一种可能是 你这个节点的等级设置的比较高， 数据库里没有和这个等级匹配的user

**Comment by mosluce** [comment]
进行

```shell
python server.py
```

输出下列错误讯息

``` shell
2018-04-25 03:27:59 ERROR    web_tools.py:36 接口返回值不正确:{"ret": -1}
2018-04-25 03:27:59 ERROR    web_tools.py:37 请求头：/nodes/1
2018-04-25 03:27:59 WARNING  web_transfer.py:264 没有查询到满足要求的节点，请检查自己的node_id!,或者该节点流量已经用光,当前节点ID:1
```

目前设置如下，是否什么步骤操作错误？

- sspanel branch : dev 
- shadowsocksr branch : master

---

绑定 admin
<img width="483" alt="2018-04-25 11 25 10" src="https://user-images.githubusercontent.com/1487051/39224849-d4399dc4-487b-11e8-95d2-c4992c44d4cc.png">
节点节点设置
<img width="498" alt="2018-04-25 11 25 59" src="https://user-images.githubusercontent.com/1487051/39224852-dbdeaf7e-487b-11e8-8be5-bdd47ff062ac.png">
后端设置
<img width="627" alt="2018-04-25 11 26 36" src="https://user-images.githubusercontent.com/1487051/39224859-e3440fa2-487b-11e8-931a-da78874c5cd9.png">

---
