### ISSUE TITLE
大佬，安装出错

### ISSUE THREAD

**Issue by hanyiwang** [Ehco1996/django-sspanel#104]
(venv-sspanel) [root@ss]# pip install -r requirements.txt
Collecting astroid==1.6.0 (from -r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/20/df/b230d15af5eadddeda595a5ceac2d51273f3df21ad207e27e346dc384ce2/astroid-1.6.0-py2.py3-none-any.whl
Collecting certifi==2017.7.27.1 (from -r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/40/66/06130724e8205fc8c105db7edb92871c7fff7d31324d7f4405c762624a43/certifi-2017.7.27.1-py2.py3-none-any.whl
Collecting chardet==3.0.4 (from -r requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Collecting cycler==0.10.0 (from -r requirements.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/f7/d2/e07d3ebb2bd7af696440ce7e754c59dd546ffe1bbe732c8ab68b9c834e61/cycler-0.10.0-py2.py3-none-any.whl
Collecting Django==2.0 (from -r requirements.txt (line 5))
  Downloading https://files.pythonhosted.org/packages/44/98/35b935a98a17e9a188efc2d53fc51ae0c8bf498a77bc224f9321ae5d111c/Django-2.0-py3-none-any.whl (7.1MB)
    99% |████████████████████████████████| 7.1MB 10.0MB/s eta 0:00:01/root/.pyenv/pyenv.d/exec/pip-rehash/pip: line 20:  2954 Killed                  "$PYENV_COMMAND_PATH" "$@"
(venv-sspanel) [root@ss]#

每次到99……

**Comment by hanyiwang** [comment]
CentOS Linux 7.0.1406
MySQL 5.5
Nginx 1.12
PHP7
宝塔面板

**Comment by Ehco1996** [comment]
这个看上去 好像是pyenv没配置好

觉得配置麻烦 可以试试docker版本
