### ISSUE TITLE
请教，前后端正常运行时内存占用多少属于正常。

### ISSUE THREAD

**Issue by mcself** [Ehco1996/django-sspanel#105]
您好，很抱歉麻烦到您，我现用的VPS为vultr  512M内存 vps，当我启动django-sspanel和shadowsock以后，我的VPS 内存占用差不多98%，请问正常情况应该是多少？

**Comment by Ehco1996** [comment]
512内存不适合做站，至少需要1g

**Comment by mcself** [comment]
好的~谢谢回复
