### ISSUE TITLE
大神，看下是我姿势的问题吗

### ISSUE THREAD

**Issue by cheapssr** [Ehco1996/django-sspanel#11]
随机端口那个我提过了
签到按钮，点击签到之后，弹出签到成功页面，点击确定。
然后刷新页面，会弹出签到失败，刷新一次，弹出一次。
资料编辑
修改协议之后，点击提交按钮，然后刷新页面，总是弹出已经修改成功的页面。刷新一次，弹出一次。
修改混淆，修改加密方式，都这样
希望刷新之后，不弹出各种提示，，因为点击之后，已经弹出过一次提示框了，刷新的话，不应该再次弹出的。

**Comment by cheapssr** [comment]
工单管理也是
按钮点击之后，刷新一次，弹出一次提示框，是常态。。

**Comment by Ehco1996** [comment]
[fixs](https://github.com/Ehco1996/django-sspanel/commit/aa8d52be1515a36f1c45f794b607458f1fb01fd8)
