### ISSUE TITLE
关于负载均衡的疑问

### ISSUE THREAD

**Issue by cheapssr** [Ehco1996/django-sspanel#12]
节点我搭建了2个，面板id都为1。
如果服务器地址填写ip地址的话，填写后端1的ip，那么，后端2号是可以正常访问的，前台不会计算后端2号的流量消耗。
01
我的疑问是，，如果我用一个域名做为服务器地址。。联通和电信，dns解析不同的后端ip，，那么流量计费正常吗？
02
如果遇到懂技术的用户，他通过域名不同的解析，找到后端ip，，那么，他直接用ip，会不会出现一个不计费的线路

03
这是2个后端的情况，如果多个后端呢？

**Comment by Ehco1996** [comment]
01 id不能设置相同
02 不会
03 不会
