### ISSUE TITLE
运行uwsgi uwsgi.ini时报错

### ISSUE THREAD

**Issue by pymdv** [Ehco1996/django-sspanel#124]
(venv-sspanel) [root@localhost django-sspanel]# uwsgi uwsgi.ini
[uWSGI] getting INI configuration from uwsgi.ini
*** Starting uWSGI 2.0.15 (64bit) on [Wed May 23 10:05:35 2018] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-28) on 23 May 2018 00:07:43
os: Linux-3.10.0-862.2.3.el7.x86_64 #1 SMP Wed May 9 18:05:47 UTC 2018
nodename: localhost.localdomain
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 8
current working directory: /home/www/django-sspanel
writing pidfile to /tmp/django-sspanel.pid
detected binary path: /root/.pyenv/versions/3.6.3/envs/venv-sspanel/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /home/www/django-sspanel # 切换到代码目录
chdir(): No such file or directory [core/uwsgi.c line 2591]
VACUUM: pidfile removed.
chdir(): No such file or directory [core/uwsgi.c line 1613]
这个报错是什么原因，求解决

**Comment by Littleccool** [comment]
跟我一样。

**Comment by pymdv** [comment]
谢谢，已经解决

**Comment by Hanbky** [comment]
如何解决的

**Comment by luoyudong593** [comment]
> 把 # 切换到代码目录这个注释去掉就可以了

非常感谢。
