### ISSUE TITLE
后端运行出现问题，请帮忙看看。

### ISSUE THREAD

**Issue by vggh66** [Ehco1996/django-sspanel#127]
[root@server1 shadowsocksr]# python server.py
IPv6 support
Traceback (most recent call last):
  File "server.py", line 74, in <module>
    main()
  File "server.py", line 54, in main
    if get_config().API_INTERFACE == 'mudbjson':
AttributeError: 'NoneType' object has no attribute 'API_INTERFACE'

**Comment by Ehco1996** [comment]
升级python版本 >= 2.7

**Comment by vggh66** [comment]
感谢大神！虽然因不太熟悉，升级版本一波三折最后终于升级成了。运行后端没问题了。
