### ISSUE TITLE
定时任务出错

### ISSUE THREAD

**Issue by 3e4r5t6y** [Ehco1996/django-sspanel#128]
![photo_2018-05-31_22-22-55](https://user-images.githubusercontent.com/33280418/40787952-6d779aa6-6521-11e8-96e4-b902b2e47e1f.jpg)
检查网站时发现用户等级到期以后，等级没有重置为0。流量也没重置成初始流量。用户还能继续使用服务。添加定时任务的路径是不存在的，这个定时任务出错该如何修复

**Comment by Ehco1996** [comment]
可以手动执行以下定时任务看看能不能成功

查看定时任务id

`python manage.py crontab show`


```
Currently active jobs in crontab:
9679327b4a96b9bfba31640daf1d9f69 -> ('0 1 * * *', 'apps.ssserver.views.check_user_state', '>>/home/www/django-sspanel/logs/userstate.log')
6eb181b2e773a1f97ead79ddece8ad5e -> ('0 0 1 * *', 'apps.ssserver.views.auto_reset_traffic', '>>/home/www/django-sspanel/logs/trafficrest.log')
69cb9ca2e693e92e3b4c9252afffc699 -> ('15 12 * * 1', 'apps.ssserver.views.clean_traffic_log', '>>/home/www/django-sspanel/logs/trafficrest.log')
465f222002aa2ab837e58be81d960db9 -> ('30 2 * * *', 'apps.ssserver.views.clean_online_log', '>>/home/www/django-sspanel/logs/node_online.log')
4ea2c842f6c82c0c32d0dee6c1ecdd5c -> ('0 3 1 * *', 'apps.ssserver.views.clean_node_log', '>>/home/www/django-sspanel/logs/node_info.log')
```

假设你测试删除在线ip日志的定时任务，需要找打该任务的 id `465f222002aa2ab837e58be81d960db9`

`python manage.py crontab run 465f222002aa2ab837e58be81d960db9`

如果成功输出的应该是类似这样的： `all online record removed!:(7250, {'ssserver.NodeOnlineLog': 7250})`

如果该任务没有成功执行
就需要排查其他的东西，比如配置是否正确之类

**Comment by Ehco1996** [comment]
有可能是crontab 没安装

**Comment by 3e4r5t6y** [comment]
我刚刚crontab -e后已经看到定时任务成功加入在里面了。一切成败就在今晚。

**Comment by 3e4r5t6y** [comment]
应该是crontab有问题，组件包都装完了，还是不起作用，看了下crontab状态，是 running也加开机自启了

**Comment by 3e4r5t6y** [comment]
![4ngqbpe oevvk 9ne1 5 0g](https://user-images.githubusercontent.com/33280418/40877485-2a18c55c-66b4-11e8-9615-a85b0204f78c.png)
zhe这个。。

**Comment by Ehco1996** [comment]
再运行一下 `python manage.py crontab run`

**Comment by 3e4r5t6y** [comment]
依然是提示这个...
![an8n8le_ ir58ai 97jayw3](https://user-images.githubusercontent.com/33280418/40902877-10b8cb48-6808-11e8-8076-54e4a468d21c.png)

**Comment by 5wszxt** [comment]
我也提示这个。。。笑哭
crontab -e里面是下面这一堆：

1 0 * * * "/root/.acme.sh"/acme.sh --cron --home "/root/.acme.sh" > /dev/null
59 23 * * * /root/.pyenv/versions/venv-sspanel/bin/python /www/wwwroot/django-sspanel/manage.py crontab run f2783bef02bf613847d3a799fac61fae >>/www/wwwroot/django-sspanel/logs/userstate.log # django-cronjobs for configs
0 0 1 * * /root/.pyenv/versions/venv-sspanel/bin/python /www/wwwroot/django-sspanel/manage.py crontab run 1ec9b1f5c23a821d6d02fb6d07bda6cd >>/www/wwwroot/django-sspanel/logs/trafficrest.log # django-cronjobs for configs
15 12 * * 1 /root/.pyenv/versions/venv-sspanel/bin/python /www/wwwroot/django-sspanel/manage.py crontab run d36362530009633c6eefb0215d26b6f9 >>/www/wwwroot/django-sspanel/logs/trafficrest.log # django-cronjobs for configs
30 2 * * * /root/.pyenv/versions/venv-sspanel/bin/python /www/wwwroot/django-sspanel/manage.py crontab run 077519ca0f158f71c152e43e313d1b0b >>/www/wwwroot/django-sspanel/logs/node_online.log # django-cronjobs for configs
0 3 1 * * /root/.pyenv/versions/venv-sspanel/bin/python /www/wwwroot/django-sspanel/manage.py crontab run ea29ccedb400d99cbcea214326ad8c77 >>/www/wwwroot/django-sspanel/logs/node_info.log # django-cronjobs for configs
0 4 1 * * /root/.pyenv/versions/venv-sspanel/bin/python /www/wwwroot/django-sspanel/manage.py crontab run ca551a3f49fa7f16de489ccb34724034 >>/www/wwwroot/django-sspanel/logs/node_reset.log # django-cronjobs for configs
30 1 * * * /root/.pyenv/versions/venv-sspanel/bin/python /www/wwwroot/django-sspanel/manage.py crontab run 3df5a0b5271983a71b540ddbce77d754 >>/www/wwwroot/django-sspanel/logs/onlineip_reset.log # django-cronjobs for configs
~

**Comment by augustdoit** [comment]
最后怎么解决的？

**Comment by augustdoit** [comment]
怎么解决的最后？同样的问题，
手动执行单独一条没问题 ，类似 python manage.py crontab run 465f222002aa2ab837e58be81d960db9
但是 执行 python manage.py crontab run 就报错，
