### ISSUE TITLE
登陆的时候，遇到错误

### ISSUE THREAD

**Issue by cheapssr** [Ehco1996/django-sspanel#13]
禁止访问 (403)
CSRF验证失败. 请求被中断.
更多信息请设置选项DEBUG＝True。

具体情况是这样的
我打开了网站主页，然后重启了一次服务器，运行diango
登陆网站进去之后，就显示的是用户中心，刷新一下页面，出现了这个错误。。
网址是
http://www.*********.com/login/

我在浏览器里后退，还是这个网址，出现了那个进入按钮，又进入了用户中心，然后刷新啥的，都一切正常了

**Comment by Ehco1996** [comment]
这是为了防止CSRF攻击
防止用户重复提交表单
