### ISSUE TITLE
同，后台添加节点报500，附上debug

### ISSUE THREAD

**Issue by 5wszxt** [Ehco1996/django-sspanel#131]
找了一圈，发现就那一个和我一样，，但是没有看到解决方法，所以自己再发一下，
希望大佬看一下，还有上次我忘记在哪个群见到你了，，，唉，要不然直接QQ给你讲好了

Request Method: | POST
-- | --
http://myss.co/admin/ssserver/node/add/
2.0.5
IntegrityError
(1048, "Column 'password' cannot be null")
/root/.pyenv/versions/3.6.3/envs/venv-sspanel/lib/python3.6/site-packages/django/db/backends/mysql/base.py in execute, line 76
/root/.pyenv/versions/3.6.3/envs/venv-sspanel/bin/uwsgi
3.6.3
['.',  '',  '/root/.pyenv/versions/3.6.3/lib/python36.zip',  '/root/.pyenv/versions/3.6.3/lib/python3.6',  '/root/.pyenv/versions/3.6.3/lib/python3.6/lib-dynload',  '/root/.pyenv/versions/3.6.3/envs/venv-sspanel/lib/python3.6/site-packages']
星期二, 5 六月 2018 12:57:36 +0800

Variable | Value
-- | --
args | [1,  None,  None,  'CN',  0,  1,  0,  '1',  None,  '1',  'aes-128-ctr',  1.0,  'auth_chain_a',  None,  'http_simple',  None,  0,  1073741824,  '1.0GB',  0,  '0B',  1,  '谜之屋']
query | ('INSERT INTO `ss_node` (`node_id`, `port`, `password`, `country`, '  '`custom_method`, `show`, `node_type`, `name`, `info`, `server`, `method`, '  '`traffic_rate`, `protocol`, `protocol_param`, `obfs`, `obfs_param`, `level`, '  '`total_traffic`, `human_total_traffic`, `used_traffic`, '  '`human_used_traffic`, `order`, `group`) VALUES (%s, %s, %s, %s, %s, %s, %s, '  '%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)')
self | <django.db.backends.mysql.base.CursorWrapper object at 0x7ff530e41048>

等等.....

我也不晓得该截那些，，，笑哭，，小白一枚。。。

**Comment by Ehco1996** [comment]
设置好节点的password就行了，不能为空

**Comment by 5wszxt** [comment]
@Ehco1996 谢谢，昨天在群里看了就是这样子解决的，，，，遇到个新问题，就是后端跑起来的时候是接口返回值不正确，但是节点信息之类的都能获取，手机连接ssr却不能上网，，，，

**Comment by Ehco1996** [comment]
接口返回值不正确
应该就是 token 没设置对
