### ISSUE TITLE
部署时运行uwsgi报错！

### ISSUE THREAD

**Issue by MRchenone** [Ehco1996/django-sspanel#132]
大佬您好。我使用了您的教程一步步来搭建的。但是当我运行uwsgi uwsgi.ini时报错了。您能帮我看下是什么原因吗？我的系统是centos7的，vps是vutrl的

![default](https://user-images.githubusercontent.com/25130831/41206192-1324062e-6d33-11e8-94dd-83b912755c41.png)

**Comment by number018** [comment]
把 uwsgi.ini里的 moudle一行改为
module = apps.wsgi:application

之前有人问过这个问题了

**Comment by MRchenone** [comment]
您好。我按照您给的建议将修改为module = apps.wsgi:application了。但是依旧报错，我把uwsgi.ini的内容贴出来您可以看下吗
![image](https://user-images.githubusercontent.com/25130831/41232054-acdd9cb0-6db7-11e8-86db-a708fab4d162.png)

**Comment by MRchenone** [comment]
看到大佬的apps目录里的wsgi.py里的内容确实是应该module = apps.wsgi:application 但我修改后依旧报错提示没有这样的模块apps
![image](https://user-images.githubusercontent.com/25130831/41233679-bf37c278-6dbc-11e8-8c59-3afccfde5426.png)

**Comment by MRchenone** [comment]
![image](https://user-images.githubusercontent.com/25130831/41233764-f674ab52-6dbc-11e8-931a-3949b3af893c.png)

**Comment by number018** [comment]
把uwsgi.ini 里面  # 以及后面的注释内容全部删除

**Comment by MRchenone** [comment]
好像还是不行。域名我也绑定了
![image](https://user-images.githubusercontent.com/25130831/41234564-216ca718-6dbf-11e8-8137-9506112d629e.png)

**Comment by number018** [comment]
我下午才测试搭建的，所有设置全部正确后，和你一样的错误，No Moudle 什么的。然后翻了翻 issue 就改了我刚说的那两个，就ok了。不太清楚你的具体配置

**Comment by MRchenone** [comment]
嗯。谢谢
