### ISSUE TITLE
我不知改了什么文件，节点信息地区的国旗图标不显示了。

### ISSUE THREAD

**Issue by vggh66** [Ehco1996/django-sspanel#134]
能告知下哪个文件是关于地区图标的吗？

**Comment by Ehco1996** [comment]
是cdn失效了
更换一下就好

**Comment by vggh66** [comment]
大神！这个CDN没搞懂，我用cloudflare，显示图这样的应该是有效的，需要到域名管理改的NS服务器也是改好了的。
![qq 20180614105409](https://user-images.githubusercontent.com/35464331/41389092-86d4e86e-6fc1-11e8-8044-22cd2288b85b.png)
