### ISSUE TITLE
User has no ss_user.

### ISSUE THREAD

**Issue by liwei01** [Ehco1996/django-sspanel#135]
http://127.0.0.1:8000/sspanel/users/userinfo/

Request Method: | GET
-- | --
http://127.0.0.1:8000/sspanel/users/userinfo/
2.0.5
RelatedObjectDoesNotExist
User has no ss_user.
C:\Python\Python36\lib\site-packages\django\db\models\fields\related_descriptors.py in __get__, line 389
C:\Python\Python36\python.exe
3.6.1
['D:\\python\\django-sspanel-master',  'D:\\python\\django-sspanel-master',  'C:\\Python\\Python36\\python36.zip',  'C:\\Python\\Python36\\DLLs',  'C:\\Python\\Python36\\lib',  'C:\\Python\\Python36',  'C:\\Users\\shusangyuan\\AppData\\Roaming\\Python\\Python36\\site-packages',  'C:\\Python\\Python36\\lib\\site-packages']

**Comment by 3e4r5t6y** [comment]
你有没有/admin添加用户

**Comment by liwei01** [comment]
已添加用户，而且已登陆

**Comment by Ehco1996** [comment]
admin用户需要在后台绑定一下 ssuser
