### ISSUE TITLE
国家地区列表问题

### ISSUE THREAD

**Issue by Okeyja** [Ehco1996/django-sspanel#138]
国家列表里有的国家，比如摩洛哥、南非这些国家，根本不会去买到他们的数据中心的，可以去除了，更大的问题在于，列表里面没有美国。惹。

**Comment by augustdoit** [comment]
apps/constants.py  里设置
加美国的话加一行  	('US','美国'),
不想要的国家自己删就好

**Comment by Ehco1996** [comment]
fixed
