### ISSUE TITLE
账号等级到期了依然可以使用的问题，请问如何Debug

### ISSUE THREAD

**Issue by pymdv** [Ehco1996/django-sspanel#139]
![qq 20180616102945](https://user-images.githubusercontent.com/39541947/41495511-cddc4c84-715b-11e8-8586-a6740f31c7e1.png)
按照教程部署的

**Comment by vggh66** [comment]
我也有这个问题，看看作者大大怎么说了。

**Comment by Ehco1996** [comment]
项目目录下有一个logs 文件夹
里面记录了 计划任务的日志
可以看一下日志

另外这个问题 以前的issue里有一个相关的
你们可以搜出来参考一下

**Comment by pymdv** [comment]
我通过修改系统时间测试，等级确实回0，网络也终止，但是有时候定时任务会失效，是不是因为我使用Xshell 6输入的命令，断开会话后，定时任务就会失效？
图里的logs应该是在18号23点59分等级到期，但是我重复输入定时命令，把时间调到19号23点59分，等级就到期了[
![qq 20180617144210](https://user-images.githubusercontent.com/39541947/41505499-16c26fbe-723d-11e8-8fd5-52aae881b5f6.png)
](url)

**Comment by 3e4r5t6y** [comment]
作者老哥。python manage.py crontab run 之后，提示无法找到任务的hash值，老哥有没有可能是你crontab解析job_hash有bug啊。
