### ISSUE TITLE
提个小建议

### ISSUE THREAD

**Issue by xyxc0673** [Ehco1996/django-sspanel#140]
就是现在 login 那个登录的 views 最后登录成功不是用 render 吗？那样的话登录成功 url 就还会停留在 /login，这时的 template 和另一个 url user/info 对应的template 是一样的。换句话说也就是 1 个 template 对应了 2 个视图。
建议是 登录成功 后，用 HttpResponseRedirect 配合 reverse 跳转到 user/info 去，至于登录成功的提示框可以用 django 里面的一个叫 messages 的类来传递消息。
以上。

**Comment by Ehco1996** [comment]
欢迎pr
