### ISSUE TITLE
我使用的django-sspanel版本和现在的不一样哦，有些问题。

### ISSUE THREAD

**Issue by vggh66** [Ehco1996/django-sspanel#141]
备份好数据库，是无法导入现在的版本的会出错。
配置文件是这样的如图
![qq 20180618182017](https://user-images.githubusercontent.com/35464331/41531076-caf6fb0c-7324-11e8-8716-e120f8ed1138.png)
我使用的这个版本我查了下定时任务也没开启吧，LOGS里2个文件都0字节。

**Comment by YGdevi** [comment]
重新装吧 最近我升级了下 发现 不如重新来一次

**Comment by vggh66** [comment]
是可以重装，但是好像之前版本的数据库导不过来。

**Comment by vggh66** [comment]
请问下使用这个版本，怎么启动定时任务呢

**Comment by vggh66** [comment]
发现到期后还可以使用
