### ISSUE TITLE
节点信息页面（nodeinfo.html） 在线用户数不准确

### ISSUE THREAD

**Issue by augustdoit** [Ehco1996/django-sspanel#143]
后台-在线IP数 跟用户界面-节点信息在线用户数  这两个差很多，用户界面那个不准确 
对应的nodeinfo.html 中的{{ list.count }} ，这个我就不懂了

                    <div class="card-footer">
                        ..........
                        <a class="card-footer-item">
                            <span class="icon">
                                <i class="fa fa-user-o">「{{ list.count }}」</i>
                            </span>
                        </a>
                    </div>

**Comment by augustdoit** [comment]
![node](https://user-images.githubusercontent.com/26730369/41698415-d6e7b888-7550-11e8-9c89-f155b580d865.jpg)

**Comment by vggh66** [comment]
你这个在线IP怎么弄得，我这项里面空空。

**Comment by augustdoit** [comment]
你用的master版本吧，我用的dev

**Comment by vggh66** [comment]
我原来是master版本，现在也是dev了，怎么就没在线IP,里面空的

**Comment by augustdoit** [comment]
汗 我也不清楚，6月17号装的dev版可以显示，7月7号更新以后尝试master也不显示

**Comment by vggh66** [comment]
嗯，这个不知道和数据库有关系吗，我看数据库里ssserver_aliveip里面没什么东西。

**Comment by vggh66** [comment]
点ssserver_aliveip没东西，里面有字段和索引2项，然后都2项里都有一样的内容下图显示
![qq 20180710093042](https://user-images.githubusercontent.com/35464331/42484139-08566c3e-8424-11e8-860e-e81870620cc2.png)

**Comment by augustdoit** [comment]
我的数据库里有，我也不知怎么解决，等等别人回复吧。

**Comment by vggh66** [comment]
目前这个问题挺多的，解决一样发现还有别的问题，我看就将就用一下得了，等成熟点的版本出了再更新。
