### ISSUE TITLE
请问后端能否使用ss呢

### ISSUE THREAD

**Issue by 497131664** [Ehco1996/django-sspanel#144]
现在原版的SS在play商店还在更新，我使用SS manyuser后端的话，用API连接前端，提示Jun 23 03:30:40 ERROR Except thrown while pulling user data:No JSON object could be decoded，应该怎么处理呢

**Comment by 497131664** [comment]
Jun 23 03:15:28 INFO Multi-User Shadowsocks Server Starting...
Jun 23 03:15:28 INFO Current Server Version: 3.4.0-4-g0914bbb

Jun 23 03:15:28 INFO Now using MultiUser API as the user interface
Jun 23 03:15:28 INFO Now starting manager thread...
Jun 23 03:15:33 INFO Now starting user pulling thread...
Jun 23 03:15:33 ERROR Except thrown while pulling user data:No JSON object could be decoded
Jun 23 03:15:38 INFO Now starting user pushing thread...
Jun 23 03:15:38 ERROR Except thrown while pushing user data:No JSON object could be decoded
Jun 23 03:16:06 ERROR Except thrown while pulling user data:No JSON object could be decoded
Jun 23 03:16:36 ERROR Except thrown while pulling user data:No JSON object could be decoded
Jun 23 03:17:06 ERROR Except thrown while pulling user data:No JSON object could be decoded

**Comment by Ehco1996** [comment]
ss manyuser  不是已经不维护了么？
你看到的版本 仓库地址在哪？

**Comment by 497131664** [comment]
https://github.com/fsgmhoward/shadowsocks-py-mu

**Comment by 497131664** [comment]
那现在前端支持那个版本的SS呢

**Comment by Ehco1996** [comment]
我仓库里的后端 是兼容ss的

**Comment by 497131664** [comment]
我昨天尝试了下，按照提示选择混肴方式后，原版SS不能连接，后端提示不能正确处理请求头

**Comment by 497131664** [comment]
能否请教下怎么样才能够使用原版SS连接呢

**Comment by crazyevent** [comment]
原版SS客户端连接的话，加密随便，协议用plain，混淆选http_simple_compatible。

**Comment by pcwuyu** [comment]
**协议里面没有plain,只有origin.混淆里面才有plain**
![wx20180826-231239](https://user-images.githubusercontent.com/6291329/44629697-9e841180-a985-11e8-9ff9-699bd5e4f6d1.png)

**Comment by SSR6** [comment]
你的后端是指？





At 2018-10-29 06:58:04, "Ehco" <notifications@github.com> wrote:


Closed #144.
