### ISSUE TITLE
运行uwsgi.ini出现这样的效果，用“域名/admin”访问显示page not found

### ISSUE THREAD

**Issue by Tomit121017** [Ehco1996/django-sspanel#155]
用“ip地址/admin”访问也是一样的不行

![wechat screenshot_20180719193828](https://user-images.githubusercontent.com/34420226/42940304-8d63e6ea-8b8b-11e8-9ee4-5ea25f82493b.png)

**Comment by Ehco1996** [comment]
Nginx没配置对
