### ISSUE TITLE
在后台删除用户，数据库不会更新？

### ISSUE THREAD

**Issue by MikuShare** [Ehco1996/django-sspanel#159]
我在后台删除了一个用户，然后再用这个昵称注册的时候提示已经被注册了。
后台看是确实只剩下一个了，但是数据库还有两个，而且用被删除的用户名登录可以登录上，输入用户名密码之后跳转500页面，然后点浏览器的返回，提示登录成功。虽然有些功能用不了，但是查看公告，联系站长，捐赠付费，充值界面，商品界面，购买记录，邀请管理，返利记录，这些功能都可以用。不知道算不算bug
![_20180722135318](https://user-images.githubusercontent.com/25380989/43042785-bdbe098c-8db7-11e8-9071-d9b0fa849dd5.png)
![_20180722135334](https://user-images.githubusercontent.com/25380989/43042786-c037b1c2-8db7-11e8-8c10-717c2d44d138.png)
![_20180722135306](https://user-images.githubusercontent.com/25380989/43042788-c3688402-8db7-11e8-902d-306d5443ffee.png)

**Comment by Ehco1996** [comment]
我刚才去测试了一下 ，貌似不能复现
问一下 你是怎么删除用户的？

**Comment by MikuShare** [comment]
在/admin页面，SSSERVER，SS用户，点修改，选中用户，然后删除。
![qq 20180723153733](https://user-images.githubusercontent.com/25380989/43063449-6186e76a-8e8e-11e8-906c-1164c8ed5947.png)

**Comment by Ehco1996** [comment]
删除ssuser不会集连删除user

如果要删除一个用户 需要删user 而不是ssuser
