### ISSUE TITLE
当节点数量超过6个时候webapi和mysql直连方式无法正常获取用户信息

### ISSUE THREAD

**Issue by jizhi1** [Ehco1996/django-sspanel#161]
如题。我今天想新增两个节点。node_id为6和7。但是无论通过webapi模式还是mysql直连方式都无法正常获取用户信息。检查了好几遍。token正确。数据库密码也正确。第五个就可以。第六个 开始。data数组就为空。。请问该如何解决
![5](https://user-images.githubusercontent.com/31647663/43121522-a3628744-8f50-11e8-8548-b23930f7ba55.png)
![6](https://user-images.githubusercontent.com/31647663/43121523-a415e564-8f50-11e8-8d8b-1630562f9765.png)

**Comment by Ehco1996** [comment]
重启一下服务器

**Comment by jizhi1** [comment]
重启就好了，已经解决。谢谢！
