### ISSUE TITLE
账号未到期续费会保留剩余流量

### ISSUE THREAD

**Issue by Creedowl** [Ehco1996/django-sspanel#162]
我设置一个月50g，到期前续费购买商品总流量变成100g且剩余时间延长了一个月。请问这是我配置的问题还是bug？

**Comment by Ehco1996** [comment]
就是这样设计的

**Comment by Creedowl** [comment]
那有没有办法设置成每月重置流量？

**Comment by crazyevent** [comment]
这个我感觉更好，不续费就清0，续费保留剩余流量，刺激用户续费。

**Comment by SSR6** [comment]
这个暂时不用理会，后期会修复，谢谢提醒。


At 2018-10-29 06:58:15, "Ehco" <notifications@github.com> wrote:


Closed #162.
