### ISSUE TITLE
为什么搭建完成后会出现Server Error (500)错误

### ISSUE THREAD

**Issue by gtx980** [Ehco1996/django-sspanel#163]
[pid: 29983|app: 0|req: 13/37] 14.144.XX.XX () {44 vars in 912 bytes} [Mon Aug  6 23:29:29 2018] GET /sspanel/nodeinfo/ => generated 27 bytes in 14 msecs (HTTP/1.1 500) 4 headers in 126 bytes (3 switches on core 9)
我在登陆的时候出现500错误，然后按了浏览器的返回就成功登陆了，我尝试了点击其他的选项有部分出现500错误

**Comment by gtx980** [comment]
看了大半天的也没搞定

**Comment by lijunhon** [comment]
解决了吗
