### ISSUE TITLE
发现一个有点严重的问题

### ISSUE THREAD

**Issue by MikuShare** [Ehco1996/django-sspanel#164]
不知道这个算不算bug
用户购买了高等级的商品，然后再买个低等级的商品，就会被降级。
比如一个商品购买之后等级是3，有效期1年；还有一个等级是1，有效期30天。
用户购买了等级3的商品，帐号等级是一年有效期，然后用户再购买一个等级1的商品，这个时候用户的等级会被重置为1，然后有效期重置回30天。并且看不到高等级的节点。
个人建议是高等级不允许购买低等级的商品。。。简单粗暴。。。

**Comment by Ehco1996** [comment]
可以加个提示之类~不过我懒得改了
