### ISSUE TITLE
配置文件疑似被覆盖导致无法连接数据库

### ISSUE THREAD

**Issue by violarulan** [Ehco1996/django-sspanel#165]
https://github.com/Ehco1996/django-sspanel/wiki/%E9%9D%A2%E6%9D%BF%E9%83%A8%E7%BD%B2 按照此篇教程部署后登录 /admin 一直是 500，打开 debug 后发现是 MySQL 的 Access Denied

于是改源码 print 出 conn_param

`{'conv': { /* ............. */, 'charset': 'utf8mb4', 'user': 'shadowsocks', 'db': 'ss_panel', 'passwd': 'your_pass', 'host': '127.0.0.1', 'port': 3306, 'client_flag': 2, 'autocommit': True, 'init_command': "SET sql_mode='STRICT_TRANS_TABLES'"}`

（至少）passwd 字段和 db.py 中内容不一致

**Comment by Ehco1996** [comment]
生产环境下
数据库的配置是从 `configs/production.py`读的
