### ISSUE TITLE
你好，作者大大！访问用户中心以及登陆之后都会500错误

### ISSUE THREAD

**Issue by a1437272595** [Ehco1996/django-sspanel#166]
访问用户中心，登录后，注册后都会500错误并且在admin页面添加的用户也无法登陆，开了纠错模式说是用户没有ss_user，请问怎么解决呢？我需要做些什么？谢谢大佬
![default](https://user-images.githubusercontent.com/40733930/44092993-a63db370-a004-11e8-8a8d-2f9ff84d5005.PNG)

**Comment by a1437272595** [comment]
emm好吧才想起来怎么绑定ssuser

**Comment by lijunhon** [comment]
老哥，咋解决的啊
