### ISSUE TITLE
为什么ssr订阅填写的是我的网址但是却更新失败

### ISSUE THREAD

**Issue by a1437272595** [Ehco1996/django-sspanel#167]
为什么ssr订阅填写的是我的网址但是却更新失败，放在ssr里面就说更新失败==

**Comment by hyjsos** [comment]
这个面板，wingdows订阅没法用。

**Comment by SSR6** [comment]
如果能正常使用就不用去管它，有时候是因为网络问题问题引起的。






At 2018-10-29 06:58:26, "Ehco" <notifications@github.com> wrote:


Closed #167.

**Comment by tataki** [comment]
同样的，我也存在这问题。还有pc扫码貌似也有bug.我之后再去试试

<https://maas.mail.163.com/dashi-web-extend/html/proSignature.html?ftlId=1&name=vycz&uid=vycz%40outlook.com&iconUrl=https%3A%2F%2Fmail-online.nosdn.127.net%2Fqiyelogo%2FdefaultAvatar.png&items=%5B%22%E9%82%AE%E7%AE%B1vycz%40outlook.com%22%5D>
[https://mail-online.nosdn.127.net/qiyelogo/defaultAvatar.png]
vycz

邮箱vycz@outlook.com


签名由 网易邮箱大师<https://mail.163.com/dashi/dlpro.html?from=mail88> 定制

在2018年11月01日 01:31，SSR6<mailto:notifications@github.com> 写道：
如果能正常使用就不用去管它，有时候是因为网络问题问题引起的。






At 2018-10-29 06:58:26, "Ehco" <notifications@github.com> wrote:


Closed #167.
