### ISSUE TITLE
部署节点时遇到问题No such file or directory

### ISSUE THREAD

**Issue by gtx980** [Ehco1996/django-sspanel#169]
![pk9vwqi_e3 s d bg lcn3](https://user-images.githubusercontent.com/36437375/44447799-def92d80-a61b-11e8-839a-885efafc7d9b.png)
系统是centos7的
这是怎么回事？？

**Comment by hyjsos** [comment]
明摆着，告诉你，没找到你要运行的文件。你到目录里去看看有没有你要的文件
