### ISSUE TITLE
后台的用户列表打开报500

### ISSUE THREAD

**Issue by hyjsos** [Ehco1996/django-sspanel#171]
系统用的centos7 ，安装后这个面板稳定运行2月有余了，今天进入后台，突然发现 用户列表 一栏点击后直接报500.其它的选项都正常。就这个用户列表进不去。不知道大佬有啥指点没。小弟不胜感激。
debug信息如图
![500](https://user-images.githubusercontent.com/34772779/44959025-0228b480-af1b-11e8-949b-2da105ef8845.png)

![debug](https://user-images.githubusercontent.com/34772779/44959178-37ce9d00-af1d-11e8-8196-eb2195cd75f4.png)

**Comment by hyjsos** [comment]
今早我清理了40幾個僵尸用戶后。用戶列表神奇的又可以打開了。不過DEBUG圖，大佬可以參考一下。

**Comment by hyjsos** [comment]
找到問題了，不知道是哪個新註冊用戶出現了BUG,因為他排在用戶列表的第一頁，所以打不開。如果直接使用 https://xx.xx.xx/sspanel/backend/userlist/?page=2，打開用戶列表第2頁就OK了，用戶太多也沒去排查到底是什麼樣的用戶會出現這種bug。索性直接把新第一頁的新註冊用戶全刪除了。

**Comment by Ehco1996** [comment]
更新到最新的dev分支，我已经将注册流程原子化了，可以避免这个问题

**Comment by hyjsos** [comment]
再问个小白的问题，怎么由现有master分支更新到dev分支

**Comment by Ehco1996** [comment]
现在master 已经同步dev了

如果要更新dev的话  可以这样
`git pull origin dev`

**Comment by hyjsos** [comment]
感謝大佬的指教。git pull像圖片中的那種結果，是否有問題？
![error](https://user-images.githubusercontent.com/34772779/44969219-c7f0fe80-af7e-11e8-9c93-50f0156d0e01.png)

**Comment by Ehco1996** [comment]
你需要先commit下自己的改动，具体可以学习一下怎么用git
