### ISSUE TITLE
WINDOWS客户端无法订阅的详细分析

### ISSUE THREAD

**Issue by Okeyja** [Ehco1996/django-sspanel#172]
ShadowsocksR的WINDOWS客户端只识别txt文件，而且是attachment方式下载的plain/text文件，才能被客户端接收。
用户订阅地址请求到的响应头应该包含
Content-Disposition: attachment; filename=文件名.txt
Content-Type: application/octet-stream; charset=utf-8
我尝试通过配置nginx vhost的location，

location ^~ /server/subscribe/ {
        add_header Content-Disposition: "attachment;";
        add_header Content-Type: "application/octet-stream; charset=utf-8";
}

重启nginx后访问订阅网址，nginx返回了一个404。
那么问题来了，根据以上的分析，请问作者我应该怎样设置我的nginx，以适配windows客户端？

**Comment by Okeyja** [comment]
P.S. 在add_header Content-Disposition: "attachment;";中配置过filename，但是一样的报404。

**Comment by Ehco1996** [comment]
虽然我已经合了
但这并不是bug
这明显是ssr win客户端的问题
