### ISSUE TITLE
开机自启怎么弄啊  大佬

### ISSUE THREAD

**Issue by sunmorg** [Ehco1996/django-sspanel#176]
开机自启怎么弄啊  大佬

**Comment by seigwen** [comment]
在init.d里写个自动启动uwsgi服务的脚本就行了, 然后chkconfig --add.

**Comment by hyjsostop** [comment]
centos7的方法，其它系系统可参考
新建一个sh后缀的文件   ，文件中输入以下内容：
#!/bin/bash
cd /你的站点目录
screen -dmS uwsgi uwsgi uwsgi.ini    （前提你已经安装screen）

然后 
 vi /etc/rc.d/rc.local
在里面加入你创建需要开机自启的sh文件，比如你的ssh文件名为 1.sh，路径在root更目录，那么输入：
bash /root/1.sh
