### ISSUE TITLE
中文用户名的订阅链接后缀可能会存在/ 被当作路径了

### ISSUE THREAD

**Issue by aexbit** [Ehco1996/django-sspanel#178]
使用中文或存在中文的用户名的订阅链接可能会是这样https://xxxx/server/subscribe/eGl/3NA/==
/被当作路径了 导致无法订阅 至少在shadowrocket上订阅会提示not found
暂时只在用户名含中文的账户上发现这个问题
目前好像是通过转换得到的固定链接是否可以把订阅链接后缀换成全随机
大佬幸苦了

**Comment by Ehco1996** [comment]
@aexbit 
dev分支已经能够支持中文了~
