### ISSUE TITLE
后台服务器自定义加密问题

### ISSUE THREAD

**Issue by Qinnnnnn** [Ehco1996/django-sspanel#18]
节点自定义加密为0的时候，依然可以用户自定义节点的加密方式

**Comment by Ehco1996** [comment]
这个需要修复
得看看ssr的源码才能解决了

**Comment by Ehco1996** [comment]
[fixed](https://github.com/Ehco1996/django-sspanel/commit/148f132f7f5c69b7435d11c7c21acc91bcf79dce)
