### ISSUE TITLE
Server Error (500)

### ISSUE THREAD

**Issue by imshunzi** [Ehco1996/django-sspanel#180]
点忘记密码的时候报 Server Error (500) 错误

**Comment by tataki** [comment]
debug 调味false，查看下报错信息

**Comment by imshunzi** [comment]
改了 看不到  我现在是升级到最新版的

**Comment by Ehco1996** [comment]
debug 要设置成True

**Comment by imshunzi** [comment]
必须设置了啊

**Comment by Ehco1996** [comment]
是代码就没跑起来吧，runserver报的错可以贴上来

**Comment by imshunzi** [comment]
代码 正常运行，debug也开启了，邮箱也配置了 就是密码重置报Server Error (500)  也看不到错误信息，别的一切正常
(sspanel) [root@hk django-sspanel]# ps -ef|grep uwsgi.ini 
root      3863     1  0 Oct25 ?        00:00:04 uwsgi uwsgi.ini
root      4017  3863  0 Oct25 ?        00:01:35 uwsgi uwsgi.ini
root      4018  3863  0 Oct25 ?        00:02:16 uwsgi uwsgi.ini
root      4019  3863  0 Oct25 ?        00:00:15 uwsgi uwsgi.ini
root      9542  9286  0 09:09 pts/0    00:00:00 grep uwsgi.ini

(sspanel) [root@hk django-sspanel]# cat configs/production.py 
import os

from configs.default import *

DEBUG = True

DATABASES['default'].update(

(sspanel) [root@hk django-sspanel]# cat configs/default/email.py 
# 是否开启邮件功能
USE_SMTP = True

# 是否开启ssl/tls
EMAIL_USE_TLS = False
EMAIL_USE_SSL = True

# 我使用163邮箱作为smtp服务器
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 465

访问https://xxx.net/password_reset/报Server Error(500)
访问别的 不存在的路径，跳转到404页面了 没有看到 django的错误信息

**Comment by Ehco1996** [comment]
只是发邮件不行的话，应该是邮件端口没开， 
今天我有空的写一个调用http的吧

**Comment by Ehco1996** [comment]
我自己尝试了一下 smtp是能够发送成功的，如果不成功 那应该是smtp服务器没配置好

**Comment by imshunzi** [comment]
不知道是不是 防火墙的问题  用的BT面板 需要单独开启端口嘛？ 我刚试了下 还是不行，很奇怪，而且 debug开启后，访问页面 还是看不到django的报错信息。。。难道我的代码版本不对嘛？
(sspanel) [root@hk django-sspanel]# git log --pretty=oneline
2e78b70b704bc5daf313b5c6e92d7b830333c5d3 Merge branch 'dev'
3ff872ed6c70012dc89c6dc18568fa389573b3f3 update readme
我用的是 master版本的最新版

**Comment by Ehco1996** [comment]
你别看uwsgi的log，直接看runserver的log

不过代码是不可能出问题的，因为用的直接是django自带的组件
我猜可能是你vps没开对应的端口
