### ISSUE TITLE
DoesNotExist at /sspanel/users/userinfo/

### ISSUE THREAD

**Issue by finalxcode** [Ehco1996/django-sspanel#181]
Request Method: | GET
-- | --
http://xxxx/sspanel/users/userinfo/
2.0
DoesNotExist
Suser matching query does not exist.
/root/.pyenv/versions/3.6.1/envs/venv-sspanel/lib/python3.6/site-packages/django/db/models/query.py in get, line 403
/root/.pyenv/versions/3.6.1/envs/venv-sspanel/bin/uwsgi
3.6.1
['.',  '',  '/root/.pyenv/versions/3.6.1/lib/python36.zip',  '/root/.pyenv/versions/3.6.1/lib/python3.6',  '/root/.pyenv/versions/3.6.1/lib/python3.6/lib-dynload',  '/root/.pyenv/versions/3.6.1/envs/venv-sspanel/lib/python3.6/site-packages']

**Comment by Ehco1996** [comment]
什么意思

**Comment by finalxcode** [comment]
现在已经解决了，如何debug啊，有时候想直接print

**Comment by Ehco1996** [comment]
wiki里有
