### ISSUE TITLE
请问ssr用于玩外服游戏，考虑延迟和丢包率用什么加密协议混淆组合？

### ISSUE THREAD

**Issue by lianmw** [Ehco1996/django-sspanel#185]

**Comment by Ehco1996** [comment]
https://github.com/Ehco1996/django-sspanel/wiki/ShadowsocksR-%E6%8E%A8%E8%8D%90%E5%8D%8F%E8%AE%AE%E6%B7%B7%E6%B7%86%E8%AE%BE%E7%BD%AE

**Comment by hyjsos123** [comment]
不管用什么协议，加密不推荐使用none，实际情况是none会更多的消耗CPU。机场主可以采纳，散户无需理会。

**Comment by Ehco1996** [comment]
@hyjsos123  请给出none会消耗更多cpu的证明
