### ISSUE TITLE
请问下作者大大，这个二维码，配置什么都点不开什么问题？

### ISSUE THREAD

**Issue by vggh66** [Ehco1996/django-sspanel#186]
![qq 20181125130923](https://user-images.githubusercontent.com/35464331/48975781-80789b00-f0b3-11e8-9eac-beadc3f198fa.jpg)

**Comment by vggh66** [comment]
是不是因為顯示的這個錯誤
(venv-sspanel) [root@host django-sspanel]# python manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, jet, sessions, sspanel, ssserver
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0001_initial... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying auth.0009_alter_user_last_name_max_length... OK
  Applying sspanel.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying jet.0001_initial... OK
  Applying jet.0002_delete_userdashboardmodule... OK
  Applying sessions.0001_initial... OK
  Applying sspanel.0002_payrequest_qrcode_url... OK
  Applying sspanel.0003_auto_20181009_0909... OK
  Applying ssserver.0001_initial... OK
  Applying ssserver.0002_auto_20180707_2200... OK
  Applying ssserver.0003_auto_20180730_0916... OK
  Applying ssserver.0004_auto_20180930_1537... OK
/root/.pyenv/versions/venv-sspanel/lib/python3.6/site-packages/django/db/models/fields/__init__.py:1423: RuntimeWarning: DateTimeField Suser.last_check_in_time received a naive datetime (1970-01-01 08:00:00) while time zone support is active.
  RuntimeWarning)
  Applying ssserver.0005_auto_20181003_1549... OK
  Applying ssserver.0006_auto_20181003_1759... OK
  Applying ssserver.0007_auto_20181004_1032... OK
  Applying ssserver.0008_auto_20181009_0909... OK

**Comment by Ehco1996** [comment]
应该是某个js没有被正确加载

和上面的日志没关系

**Comment by vggh66** [comment]
嗯。這個不知道怎麼找問題所在呢，某個js。

**Comment by Ehco1996** [comment]
用chrome 的调试工具，看看是不是没加载出来

**Comment by vggh66** [comment]
好的，我看看。

**Comment by vggh66** [comment]
不知是不是這個,不太懂。
Refused to apply style from 'https://xxx.com/static/sspanel/css/ehco.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
2
ehcov1.js:1 Failed to load resource: the server responded with a status of 404 ()
(index):1 Refused to apply style from 'https://xxx.com/static/sspanel/css/ehco.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.

**Comment by Ehco1996** [comment]
那应该是你nginx的静态文件目录没搞定哦

**Comment by vggh66** [comment]
是伪静态吗？
location /media  
    {        
        alias /home/www/django-sspanel/media;  # 媒体文件地址
    }    
location /static
    {    
        alias  /home/www/django-sspanel/static; #静态文件地址，js/css
        expires  12h;
    }    
location /
    {    
        include uwsgi_params;        
        uwsgi_pass 127.0.0.1:8080;
    }

**Comment by vggh66** [comment]
还是
(venv-sspanel) [root@host django-sspanel]# python manage.py collectstatic

You have requested to collect static files at the destination
location as specified in your settings:

    /home/www/django-sspanel/static

This will overwrite existing files!
Are you sure you want to do this?

Type 'yes' to continue, or 'no' to cancel: yes
Found another file with the destination path 'admin/css/forms.css'. It will be ignored since only the first encountered file is collected. If this is not what you want, make sure every static file has a unique path.
Found another file with the destination path 'admin/css/base.css'. It will be ignored since only the first encountered file is collected. If this is not what you want, make sure every static file has a unique path.
Found another file with the destination path 'admin/css/rtl.css'. It will be ignored since only the first encountered file is collected. If this is not what you want, make sure every static file has a unique path.
Found another file with the destination path 'admin/css/widgets.css'. It will be ignored since only the first encountered file is collected. If this is not what you want, make sure every static file has a unique path.
Found another file with the destination path 'admin/css/changelists.css'. It will be ignored since only the first encountered file is collected. If this is not what you want, make sure every static file has a unique path.
Found another file with the destination path 'admin/css/login.css'. It will be ignored since only the first encountered file is collected. If this is not what you want, make sure every static file has a unique path.
Found another file with the destination path 'admin/css/dashboard.css'. It will be ignored since only the first encountered file is collected. If this is not what you want, make sure every static file has a unique path.
Found another file with the destination path 'admin/css/fonts.css'. It will be ignored since only the first encountered file is collected. If this is not what you want, make sure every static file has a unique path.
Found another file with the destination path 'admin/js/SelectFilter2.js'. It will be ignored since only the first encountered file is collected. If this is not what you want, make sure every static file has a unique path.
Found another file with the destination path 'admin/js/admin/RelatedObjectLookups.js'. It will be ignored since only the first encountered file is collected. If this is not what you want, make sure every static file has a unique path.
Found another file with the destination path 'admin/js/admin/DateTimeShortcuts.js'. It will be ignored since only the first encountered file is collected. If this is not what you want, make sure every static file has a unique path.

0 static files copied to '/home/www/django-sspanel/static', 399 unmodified.
(venv-sspanel) [root@host django-sspanel]#

**Comment by Ehco1996** [comment]
这两个目录要替换成你项目运行的真是目录才行

**Comment by vggh66** [comment]
是不是要改这个里面内容。以前都没改这个。
![qq 20181126164451](https://user-images.githubusercontent.com/35464331/49002541-d5dba780-f19a-11e8-8042-27a63651bb63.jpg)

**Comment by vggh66** [comment]
静态目录就是/home/www/django-sspanel/static，所以那个不用改直接用。

**Comment by vggh66** [comment]
搞了好久
指向“https://xxx.com/static/sspanel/js/ehcov1.js”的 <script> 加载失败。

**Comment by vggh66** [comment]
指向“https://xxx.com/static/jet/js/build/bundle.min.js?v=1.0.7”的 <script> 加载失败。

**Comment by Bluefissure** [comment]
strict mime的问题，那个css文件的Content-Type是'text/html'，然而加载了css，另外你的chrome的strict MIME check也打开了
可以将那个css的content-type改一下，或者关掉strict MIME check，具体方法建议Google下
参考https://stackoverflow.com/questions/39228657/disable-chrome-strict-mime-type-checking
