### ISSUE TITLE
全部Internal Server Error 500

### ISSUE THREAD

**Issue by zewenlee** [Ehco1996/django-sspanel#187]
请问各位大佬，我在使用宝塔面板+SSH下安装完，打开域名提示Internal Server Error，/admin也是，求解。

**Comment by zewenlee** [comment]
中途没有报错 数据库连接等都正确 SSH是xshell6  php7.1 mysql5.1

**Comment by Ehco1996** [comment]
可以按照wiki 吧debug模式的日志贴出来看看
