### ISSUE TITLE
Docker部署一键部署错误的相关问题

### ISSUE THREAD

**Issue by roiff** [Ehco1996/django-sspanel#188]
Dockerfile中，RUN中：python3 manage.py collectstatic --no-input 这一条，需要连接数据库，但是dokcer-compose会先build，然后才全部运行，这时候就会报错了。
我临时的删除了这个语句，放入到了CMD中。
因为只涉及到部署，就没有pull这个bug了，作者或者后人自行解决一下吧。
先试用一下

**Comment by Ehco1996** [comment]
fixed
