### ISSUE TITLE
关于用户签到疑似出现bug以及关于按钮的建议

### ISSUE THREAD

**Issue by Kurokitu** [Ehco1996/django-sspanel#189]
当用户点击签到后重新刷新浏览器时签到的状态依旧是未签到，也就意味着可以无限次签到，请问是否有这个问题。
以及关于网站上的按钮，按钮的触发只能点击文字，没有把整个按钮包括进去所以单点按钮是无效的可以考虑把按钮包括进去。

**Comment by Kurokitu** [comment]
bug问题追加：
流量排行的表格显示单位有问题
例如一位用户用了30MB
则会在表格中显示30MB GB的情况
其他表格还未检查可能还会存在。

**Comment by Ehco1996** [comment]
1 无限签到的问题我这里并不能复现，有可能是数据库时间的问题
2 第二个问题可以改一下模板，暂时没有时间做
3 已经修复了

**Comment by Ehco1996** [comment]
签到的问题应该已经解决了， 我统一用了上海市区的时间，更新到最新的代码就ok
