### ISSUE TITLE
Django 2.1 Mysql 5.5

### ISSUE THREAD

**Issue by Bluefissure** [Ehco1996/django-sspanel#191]
[Django 2.1 won't support mysql 5.5](https://docs.djangoproject.com/en/2.1/releases/2.1/#dropped-support-for-mysql-5-5)
Maybe you can specify a version of django to requirements.txt instead of the latest one
Or add some notes to the wiki

**Comment by Ehco1996** [comment]
thanks, already add to wiki home page
