### ISSUE TITLE
python manage.py migrate出错

### ISSUE THREAD

**Issue by xkatld** [Ehco1996/django-sspanel#196]
出现如图错误
<img src="https://i.loli.net/2018/12/24/5c1fc9ca77b11.png" alt="截屏_2018-12-24-01-41-48.png" title="截屏_2018-12-24-01-41-48.png" />
<img src="https://i.loli.net/2018/12/24/5c1fc9f94a66c.png" alt="截屏_2018-12-24-01-42-59.png" title="截屏_2018-12-24-01-42-59.png" />
请问该如何填写

**Comment by Bluefissure** [comment]
WTF is the "ssr_sparrow_hk_c" in the code? Where did you pull your code from?
You exposed your database password btw.

**Comment by xkatld** [comment]
我就是在需要填写的地方填写啊

**Comment by Bluefissure** [comment]
change "ssr_sparrow_hk_c" to "os.getenv" as the code [here](https://github.com/Ehco1996/django-sspanel/blob/dev/configs/development.py#L8)
