### ISSUE TITLE
使用docker安装

### ISSUE THREAD

**Issue by xkatld** [Ehco1996/django-sspanel#197]
大大你好，我先更改数据库配置文件，然后收入docker-compose up安装之后，ssh就定格在这里了，我进入域名，502，求解！
<img src="https://i.loli.net/2018/12/27/5c2484fad2b11.png" alt="截屏_2018-12-27-15-47-53.png" title="截屏_2018-12-27-15-47-53.png" />
<img src="https://i.loli.net/2018/12/27/5c24850d88408.png" alt="截屏_2018-12-27-15-17-01.png" title="截屏_2018-12-27-15-17-01.png" />
<img src="https://i.loli.net/2018/12/27/5c2485292236b.png" alt="截屏_2018-12-27-15-46-16.png" title="截屏_2018-12-27-15-46-16.png" />

**Comment by pc84560895** [comment]
修改一下 uwsigi.ini 还有configs/default/db.py 的配置即可。
