### ISSUE TITLE
生成ssr 的方法 get_ssr_link 判断是不是写反了

### ISSUE THREAD

**Issue by kyojujor** [Ehco1996/django-sspanel#200]
self.custom_method == 1:
            ssr_code = '{}:{}:{}:{}:{}:{}/?remarks={}&group={}'.format(
                self.server, ss_user.port, ss_user.protocol, ss_user.method,
                ss_user.obfs, ssr_password, ssr_remarks, ssr_group)

应该为0的时候才使用用户的自己的加密吧

**Comment by Ehco1996** [comment]
没有写反
