### ISSUE TITLE
docker部署问题

### ISSUE THREAD

**Issue by czhbeing** [Ehco1996/django-sspanel#202]
执行:docker-compose run web python manage.py createsuperuser
You have 29 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, jet, sessions, sspanel, ssserver.
Run 'python manage.py migrate' to apply them.

输入用户名后:django.db.utils.ProgrammingError: (1146, "Table 'sspanel.sspanel_user' doesn't exist")

然后执行python manage.py

  File "manage.py", line 18, in <module>
    "Couldn't import Django. Are you sure it's installed and "
ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?

大神要怎么办？ 我用docker compose安装

**Comment by Ehco1996** [comment]
要先把mysql起来之后进去把数据库简建上

**Comment by czhbeing** [comment]
我怎么知道建什么数据库呢？
还有我进不了mysql的docker 用attch会卡住不行
你这个manage.py不是可以以键构建数据库吗？
