### ISSUE TITLE
多端口的范围怎么设置

### ISSUE THREAD

**Issue by zylok520** [Ehco1996/django-sspanel#204]
site.py里面起始端口 28600
MB = 1024 * 1024
GB = 1024 * 1024 * 1024
DEFAULT_TRAFFIC = 10 * GB
START_PORT = 28600

目前测试端口是随机的，

这样设置了 注册分配的端口却是7140  15321这样的

怎么设置能够保证在可以2000-3000的这样范围

**Comment by Ehco1996** [comment]
并没有做这样的功能，端口会一直往上涨

**Comment by zylok520** [comment]
端口并没有一直往上涨 有时候往下，我感觉得是随机的

**Comment by ljxangus** [comment]
尝试了一下，发现端口号在创建账户时是随机生成的。好像没有按照 `sites.py` 里面设置的 START_PORT 来生成。
