### ISSUE TITLE
关于流量单位显示问题

### ISSUE THREAD

**Issue by Kurokitu** [Ehco1996/django-sspanel#209]
在之前的Issues提到的关于浏览记录单位出现双单位的问题在拉取新的代码之后并没有解决，依旧出现了显示9.5MB GB或9.5GB GB的类似情况。

**Comment by Kurokitu** [comment]
![qq 20190203230602](https://user-images.githubusercontent.com/19619713/52178348-4b519d00-2808-11e9-965c-aa38fe2c37b3.png)

**Comment by Ehco1996** [comment]
应该是你手动修改过模板文件。可以把对应的template里的单位去掉就可以了
