### ISSUE TITLE
登陆cookie不会失效的吗

### ISSUE THREAD

**Issue by cheapssr** [Ehco1996/django-sspanel#21]
我发现，只要登陆，不清理cookie，就一直可以直接进入网站。。
有cookie失效期吗

**Comment by Ehco1996** [comment]
@cheapssr 
默认没有设置失效时间
下个版本加上
60分钟怎么样？

**Comment by cheapssr** [comment]
不用那么长时间吧，，用户登陆就是看看线路啥的，最多修改一下节点加密协议。。很快就好的
个人觉得30分钟就够了。
顺便问一句，用户前台流量记录显示10条，怎么能显示的更多呢，，比如显示100条啥的。。或者最好能导出1个月的流量记录。。就像话费详单的意思

**Comment by qiqizjl** [comment]
可以默认60分钟 每次刷新页面延长时间 否则30分钟就退出一次。。有点蛋疼。。

**Comment by Ehco1996** [comment]
30分钟稍微有点短
设置为为60分钟不访问遍失效

[Fix](https://github.com/Ehco1996/django-sspanel/commit/21e6adaf6e98596cdb3df93b196ff5eeacde9e6b)
