### ISSUE TITLE
升级迁移导致生产环境严重故障无法使用

### ISSUE THREAD

**Issue by Okeyja** [Ehco1996/django-sspanel#210]
按照[wiki](https://github.com/Ehco1996/django-sspanel/wiki/%E9%87%8D%E5%A4%A7%E6%9B%B4%E6%96%B0%E6%AD%A5%E9%AA%A4)的升级办法，运行
`python manage.py migrate`
后运行
`python manage.py shell`
```python
from apps.ssserver.models import SSUser
for u in SSUser.objects.all():
    u.sync_to_suser()
```
出现DoesNotExist at /sspanel/users/userinfo/错误
查阅源代码后发现并没有SSUser的函数或类，应当为Suser。
请作者更正wiki，并尽快提供恢复方案，谢谢。

**Comment by Okeyja** [comment]
```python
from apps.ssserver.models import Suser
for u in Suser.objects.all():
    u.sync_to_suser()
```
运行更正后的代码后无反应，估计数据已经丢失。

**Comment by Ehco1996** [comment]
需要严格按照wiki的步骤来，你没有更新到对应的commit

**Comment by Okeyja** [comment]
丢失的业务无法恢复，已通过补充数据将系统运转。
关闭issue。
