### ISSUE TITLE
嗯，，，提个建议

### ISSUE THREAD

**Issue by cheapssr** [Ehco1996/django-sspanel#22]
单端口多用户，，感觉比较重要。。。
形势

**Comment by Ehco1996** [comment]
这个暂时我也搞不了
我还没弄明白到底是怎么一回事呢

**Comment by cheapssr** [comment]
参考魔改。。。。我看不懂代码
魔改应该是用一个用户来承载所有的用户
具体的
https://lala.im/1155.html
这里有个教程
我没有明白原理。。。

**Comment by Woophp** [comment]
https://breakwa11.blogspot.jp/2017/01/shadowsocksr-mu.html
看这里才能明白原理

**Comment by Ehco1996** [comment]
@Woophp 
谢谢告知，
这篇文章我很长时间之前就看过了，
但是是通过修改配置文件达到单端口多用户的，
这个不从数据库操作的话 还是需要手动去配置的
所以我也不知道怎么整合到面板里
