### ISSUE TITLE
支付宝当面付页面 500错误怎么解决

### ISSUE THREAD

**Issue by changwangyun** [Ehco1996/django-sspanel#220]
Request Method: | GET
-- | --
https://www.tizo.ml/api/orders
2.0
AttributeError
'NoneType' object has no attribute 'check_order_status'
./apps/api/views.py in get, line 330
/root/.pyenv/versions/3.6.1/envs/venv-sspanel/bin/uwsgi
3.6.1
['.',  '',  '/root/.pyenv/versions/3.6.1/lib/python36.zip',  '/root/.pyenv/versions/3.6.1/lib/python3.6',  '/root/.pyenv/versions/3.6.1/lib/python3.6/lib-dynload',  '/root/.pyenv/versions/3.6.1/envs/venv-sspanel/lib/python3.6/site-packages']
星期二, 19 三月 2019 18:04:07 +0800

Traceback Switch to copy-and-paste view
/root/.pyenv/versions/3.6.1/envs/venv-sspanel/lib/python3.6/site-packages/django/core/handlers/exception.py in inner
            response = get_response(request) ...
▶ Local vars
/root/.pyenv/versions/3.6.1/envs/venv-sspanel/lib/python3.6/site-packages/django/core/handlers/base.py in _get_response
                response = self.process_exception_by_middleware(e, request) ...
▶ Local vars
/root/.pyenv/versions/3.6.1/envs/venv-sspanel/lib/python3.6/site-packages/django/core/handlers/base.py in _get_response
                response = wrapped_callback(request, *callback_args, **callback_kwargs) ...
▶ Local vars
/root/.pyenv/versions/3.6.1/envs/venv-sspanel/lib/python3.6/site-packages/django/views/generic/base.py in view
            return self.dispatch(request, *args, **kwargs) ...
▶ Local vars
/root/.pyenv/versions/3.6.1/envs/venv-sspanel/lib/python3.6/site-packages/django/views/generic/base.py in dispatch
        return handler(request, *args, **kwargs) ...
▶ Local vars
./apps/api/views.py in get
        order.check_order_status() ...
▶ Local vars

**Comment by Ehco1996** [comment]
是个bug 现在已经修复了
