### ISSUE TITLE
关于配置文件忽略

### ISSUE THREAD

**Issue by qiqizjl** [Ehco1996/django-sspanel#23]
目前配置都在simple_setting_product.py里。这个文件也被git版本控制所管理。在线上部署环境的时候，我们会去改动这个文件，导致git pull的时候会报冲突，目前我只能先备份。然后还原。。还原之后，如果这次更新里加了配置项，且我没同步，业务就会报错。能否做个templdate文件。然后将这个文件删除并忽略。如果配置文件有变动，在更新日志里体现。

**Comment by Ehco1996** [comment]
需要添加新的配置文件的时候，我会在本地修改好simple_setttings,再提交上去
虽然merge的时候会失败，但是只需要手动进这个文件改一下就可以了
如果全部写到更新日志里，容易让新人装的是漏掉，反而容易出错
