### ISSUE TITLE
docker版 修改或者添加服务器后 要重启panel api数据才会刷新

### ISSUE THREAD

**Issue by KleinerSource** [Ehco1996/django-sspanel#230]
例如修改了密码 服务器节点信息之类的  不重启面板的话 数据一直不刷新..web正常显示 但是
/api/users/nodes/1?token= 
/api/nodes/1?token=
中刷新 数据还是旧的. 直到重启面板才会更新

**Comment by Ehco1996** [comment]
加了5min的cache

只有用户发生购买行为之后才会更新，
修改节点配置的我还没做清cache，有空的时候我加一下

**Comment by Ehco1996** [comment]
@KleinerSource 

dev分支已经修复这个问题了
