### ISSUE TITLE
搭建好之后用户中心报错500

### ISSUE THREAD

**Issue by kakkk** [Ehco1996/django-sspanel#238]
按照萌新版和硬核版搭建之后主页能访问，但是登录用户中心都会出现500错误
但是管理中心可以用
[![ZDIA5n.png](https://s2.ax1x.com/2019/07/08/ZDIA5n.png)](https://imgchr.com/i/ZDIA5n)
[![ZDIkUs.png](https://s2.ax1x.com/2019/07/08/ZDIkUs.png)](https://imgchr.com/i/ZDIkUs)

**Comment by kakkk** [comment]
添加用户也会出现500

**Comment by lijunhon** [comment]
这个问题解决了吗？
