### ISSUE TITLE
出现个很奇怪的问题

### ISSUE THREAD

**Issue by cheapssr** [Ehco1996/django-sspanel#24]
我是管理员，一直使用管理员账号
设置商品流量包15元1G
后台修改管理员余额15元
然后购买1G流量
购买成功，自动跳转到用户中心，余额为0
然后我刷新页面，会跳转到商品页面，显示余额不足（我怀疑这是又购买一次）
我点击ok
然后回到用户中心。。余额为3.20元
测试了几次，都是这样。。

**Comment by cheapssr** [comment]
用充值码补充余额，，结果一样
我注册一个新账号试试

**Comment by cheapssr** [comment]
明白了，，原来是返利的缘故。。
20%的。。。

**Comment by cheapssr** [comment]
# 用户邀请返利比例
# INVITE_PERCENT = 0.2
我可以注释掉这个吗，，我不弄返利

**Comment by Ehco1996** [comment]
@cheapssr  把这个参数变为0就行啦
