### ISSUE TITLE
Docker版执行docker-compose up报错

### ISSUE THREAD

**Issue by Sakura-Dragon4146** [Ehco1996/django-sspanel#240]
具体操作如下
`[root@vultr django-sspanel]# docker-compose up
ERROR: Couldn't connect to Docker daemon at http+docker://localunixsocket - is it running?

If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.
[root@vultr django-sspanel]# docker-compose run web python manage.py createsuperuser
ERROR: Couldn't connect to Docker daemon at http+docker://localunixsocket - is it running?

If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.`

**Comment by Sakura-Dragon4146** [comment]
docker和docker-compose用yum安装

**Comment by Ehco1996** [comment]
docker 没有启动成功

`systemctl start docker`
