### ISSUE TITLE
docker版的订阅好像不支持v2ray

### ISSUE THREAD

**Issue by jackjieYYY** [Ehco1996/django-sspanel#246]
面板已经连上v2ray的节点

但是订阅更新并没有刷新出来  只刷出SS的

**Comment by Ehco1996** [comment]
首页可以选择订阅的类型，默认只订阅ss

**Comment by jackjieYYY** [comment]
> 首页可以选择订阅的类型，默认只订阅ss

谢谢回复。但是订阅更改提交后 没有变化 没有刷新 还是只有ss节点

**Comment by Ehco1996** [comment]
直接在浏览器打开订阅链接显示啥？
有显示vmess节点么

如果有的话说明是客户端的问题

**Comment by jackjieYYY** [comment]
> 直接在浏览器打开订阅链接显示啥？
> 有显示vmess节点么
> 
> 如果有的话说明是客户端的问题

晚上好呀

后端和前端都连上了 
![1](https://user-images.githubusercontent.com/53422254/67202926-8c044b80-f455-11e9-96cf-a0f55e34b4c2.png)

也能正常使用

这是订阅文件下载下来大的截图
只有第一个ss节点


![2](https://user-images.githubusercontent.com/53422254/67203023-c1109e00-f455-11e9-8e74-758bfa58a1d2.png)

**Comment by jackjieYYY** [comment]
还有一点就是 

vmess 这个节点的二维码打不开 等很久也没反应 有时候反而刷出来第一个ss节点的二维码

配置按钮倒是没有问题


![4](https://user-images.githubusercontent.com/53422254/67203197-3e3c1300-f456-11e9-99d7-6dae90866fe1.png)

**Comment by jackjieYYY** [comment]
> 订阅和下载配置不是一个地址
> 配置下载的功能目前只支持ss的
> 
> vmees节点配置打不开是一个bug，我修复一下会推到dev分支上去

原来如此原来如此
谢谢解答

![8{`MAXX8DM8TK$((543J36X](https://user-images.githubusercontent.com/53422254/67205865-5d3da380-f45c-11e9-976b-de483d574d90.png)
