### ISSUE TITLE
DoesNotExist at /sspanel/users/userinfo/ UserSSConfig matching query does not exist.

### ISSUE THREAD

**Issue by jackjieYYY** [Ehco1996/django-sspanel#247]
用的是普通版本搭建

打开 用户中心 或者节点列表就报错了

这是报错的信息 我上传到网盘了

![2](https://user-images.githubusercontent.com/53422254/67296560-5a15e680-f534-11e9-81b4-a7b8dfe393ab.png)

这是错误信息的整个网页👇👇👇👇👇👇👇👇
https://mute-bird-da4e.dltest.workers.dev/DoesNotExist%20at%20_sspanel_users_userinfo_.html

数据库那边应该没问题 能看到创建了几个用户

![1](https://user-images.githubusercontent.com/53422254/67296371-18853b80-f534-11e9-8137-5ea6750d9e21.png)

**Comment by Ehco1996** [comment]
不能直接在user表写数据，
会有一些数据通过虚拟外键绑定到其他表

把这个用户数据删了，通过网站注册就不会有这个问题了

**Comment by Ehco1996** [comment]
注册的时候报错了么？

**Comment by jackjieYYY** [comment]
> 注册的时候报错了么？

没有没有

其实 docker版也有这个问题

但是  service docker restart 重启一下docker 就解决了

就是普通版不知道怎么操作

**Comment by blackcatpolice** [comment]
所以没有人解决？

**Comment by blackcatpolice** [comment]
在面板注册可以，可是我通过命令创建admin 的时候怎么办呢。不通过命令建又没有邀请码。死循环 了。
