### ISSUE TITLE
v2ray订阅无法在V2rayNG使用

### ISSUE THREAD

**Issue by TheWanderingCoel** [Ehco1996/django-sspanel#248]
很抱歉又打扰大佬了,目前使用发现v2ray的订阅链接无法在V2rayNG,kitsunebi(安卓)上使用,更新订阅皆为Failure.只有Shadowrocket(ios)可以成功订阅,能否请问一下这是什么bug?

**Comment by Ehco1996** [comment]
客户端的bug 去找客户端

**Comment by TheWanderingCoel** [comment]
好的,谢谢大佬
