### ISSUE TITLE
关于V2ray tls

### ISSUE THREAD

**Issue by vance1314** [Ehco1996/django-sspanel#271]
希望可以出一期后端对接的视频 放在YouTube上

**Comment by Ehco1996** [comment]
@vance1314 
https://www.youtube.com/watch?v=QNbnya1HHU0&t=1s

**Comment by lm93129** [comment]
似乎不支持ws+tls这种方式去对接吧，比如我自己配置好v2ray，然后用sidecar对接到面板，但是面板给出的配置还是tcp这一种方式的样子

**Comment by Ehco1996** [comment]
@lm93129  面板现在还不支持ws和tls，想用的话只能手动写好v2ray的ws tls配置， 然后从配置文件启动。不能从面板启动

**Comment by Ehco1996** [comment]
现在已经支持了

**Comment by chengziorange** [comment]
> 现在已经支持了

你好！可以大概说一下要怎么通过ws+tls的方式对接吗？新建节点的时候并没看到证书相关的设置。
