### ISSUE TITLE
UserSSConfig matching query does not exist.

### ISSUE THREAD

**Issue by blackcatpolice** [Ehco1996/django-sspanel#279]
![image](https://user-images.githubusercontent.com/4312114/75411094-02abdb00-5959-11ea-8f50-890c652370cf.png)

还是这个问题，创建管理员是通过命令建的，但是有bug，直接创建又没有邀请码，死循环咯？

**Comment by Ehco1996** [comment]
`python manage.py create_admin --email "admin@ss.com" --username "admin1" --password "adminadmin"`


正确的命令是这个，你用的什么
