### ISSUE TITLE
DoesNotExist at /users/userinfo/

### ISSUE THREAD

**Issue by Baizhixi** [Ehco1996/django-sspanel#282]
萌新版安装方式，麻烦查看是什么问题
]`

Request Method: | GET
-- | --
https://uu.bgp.world/users/userinfo/
2.0
DoesNotExist
UserTraffic matching query does not exist.
/root/.pyenv/versions/3.6.3/envs/venv-sspanel/lib/python3.6/site-packages/django/db/models/query.py in get, line 403
/root/.pyenv/versions/3.6.3/envs/venv-sspanel/bin/uwsgi
3.6.3
['.',  '',  '/root/.pyenv/versions/3.6.3/lib/python36.zip',  '/root/.pyenv/versions/3.6.3/lib/python3.6',  '/root/.pyenv/versions/3.6.3/lib/python3.6/lib-dynload',  '/root/.pyenv/versions/3.6.3/envs/venv-sspanel/lib/python3.6/site-packages']
星期五, 28 二月 2020 22:28:36 +0800

`

**Comment by Ehco1996** [comment]
@Baizhixi 

创建管理员应该这样

`python manage.py create_admin --email "admin@ss.com" --username "admin1" --password "adminadmin"`

萌新版的文档忘记更新了

**Comment by Baizhixi** [comment]
![image](https://user-images.githubusercontent.com/20068143/75602088-e052c280-5afc-11ea-86b0-2677a3442d9a.png)
您好，出现这个问题

**Comment by Baizhixi** [comment]
> @Baizhixi
> 
> 创建管理员应该这样
> 
> `python manage.py create_admin --email "admin@ss.com" --username "admin1" --password "adminadmin"`
> 
> 萌新版的文档忘记更新了

您好，出现这个问题
![image](https://user-images.githubusercontent.com/20068143/75602258-6c191e80-5afe-11ea-94e4-1eba4fb38276.png)

**Comment by Ehco1996** [comment]
@Baizhixi 

应该是django-版本不对，升级一下依赖

`pip install -r requirements`
