### ISSUE TITLE
KeyError at /api/user_vmess_config/1/

### ISSUE THREAD

**Issue by blackcatpolice** [Ehco1996/django-sspanel#283]
很奇怪，服务端对接配置访问错误。

![image](https://user-images.githubusercontent.com/4312114/75603239-928f8780-5b07-11ea-971e-7870b84f8800.png)
---------------------------------------
反馈，这个放到v2scar里面 没有抛出异常。

**Comment by blackcatpolice** [comment]
我看到这个地方，似乎是user_id 没有拿到， 配置v2scar 的请求需要用到user_id吗？
还是说这个地方只有v2scar 带参数请求才可以。 

![Uploading image.png…]()

**Comment by blackcatpolice** [comment]
还有就是，我都配置好了，还是显示掉线。 是因为对接的时候有问题导致的。

**Comment by blackcatpolice** [comment]
后端按照这个配置好了， 但是面板还是显示不在线，是什么原因呢。
![image](https://user-images.githubusercontent.com/4312114/75603494-d84d4f80-5b09-11ea-96ab-7b1ee693673e.png)

**Comment by blackcatpolice** [comment]
面板和节点在两台机器上。

**Comment by Ehco1996** [comment]
@blackcatpolice  应该是你之前手动创建用户导致的
把数据库里的数据全部清掉，重新创建用户就好

**Comment by blackcatpolice** [comment]
卧槽 牛逼啊 ， 给后面的人留下句话吧， 凡是遇到问题， 先把用户数据清除，再根据最新的创建管理员命令创建 

python manage.py create_admin --email "admin@ss.com" --username "admin" --password "admin"
