### ISSUE TITLE
很喜欢这个面板，提一些建议

### ISSUE THREAD

**Issue by Baizhixi** [Ehco1996/django-sspanel#284]
搜寻gayhub的时候发现的这个面板，很喜欢，感觉功能有些缺失，提一些建议希望后期可以补充。
1. v2ray可以选择后端协议
2. v2ray可以多协议共存
3. 面板可以设定纯SS/v2ray模式，开启后隐藏相关GUI，比如纯v2ray就不显示ss的设置选项
4. 节点/商品简介里，支持HTML语言
5. 套餐/用户速度限制（好像v2本身不支持）
6. 延迟检测（由后端ping指定的几个IP）
7. 用户中心的公告栏，移到上面比较好
8. 多用户多端口
9. 签到栏不显示获取的流量范围值（可选项也可以）
10. 充值码导出
11. 设备数量限制

**Comment by Ehco1996** [comment]
欢迎pr

**Comment by amColinzzz** [comment]
这个issue提出的建议都不错，不过辛苦作者大人了，我也是一名程序员，知道改需求非常不易，希望加油。
我有个问题想咨询：
1.目前针对v2ray的限速功能是不是无效?因为v2ray本身是不支持限速的。
2.能否添加v2ray的限制设备数量的功能（其实流量限制了一样）
3.目前主流的比较安全的方式，我一直在用v2ray的ws+tls的模式科学上网，因为这样不容易被band ip。希望增加这个模式的支持。
--------------------------------------------------------------------------------
因为质量较好的CN2 GIA 都比较贵，我买的一年就上千，自己用流量用不完，借给朋友或者合租，又既不能控制流量又不能控制设备数量，怕合租的人借出去，峰值流量阻塞是小事，万一通过我的服务器进行不法活动就糟糕了。所以希望作者能通过这个面板，在外部加入对v2ray 流量峰值速度，设备数量的控制。
--------------------------------------------------------------------------------
最后，感谢作者的辛苦付出。

**Comment by Ehco1996** [comment]
@amColinzzz 

这些feature需要v2ray-core本身实现之后面板才能支持
所以应该吧feature request提到 https://github.com/v2ray/v2ray-core里

**Comment by amColinzzz** [comment]
我看到ss协议增加节点的时候 有限速功能,但是不知道能否实现限制客户端同时登录的数量?
