### ISSUE TITLE
关于推广ref与无痛升级的建议

### ISSUE THREAD

**Issue by YogiLiu** [Ehco1996/django-sspanel#289]
一、推广连接的ref值为用户id我认为不妥，因为ref为1的用户肯定存在，邀请注册机制就没意义了，任何知道ref=1的恶意用户都可以注册；
二、可否将常用配置项抽出，添加到.gitignore，以实现新版本无痛升级。

**Comment by Ehco1996** [comment]
配置文件从环境变量注入就好

**Comment by YogiLiu** [comment]
1. 一般来说，`user_id==1`是必然存在的，我认为如果使用`user_id`，应把`user_id`加盐加密，形成校验值，再把`user_id`和校验值base64运算后加入ref会比较好（此处参考jwt的实现）
2. `configs/default/sites.py`中的配置无法从环境变量注入，升级时需处理冲突
