### ISSUE TITLE
请问一下，找不到文件的修改地方了

### ISSUE THREAD

**Issue by cheapssr** [Ehco1996/django-sspanel#30]
ssinvite
这个文件在哪里修改啊，我翻遍了文件，都么有找到啊
我原来修改过一次，第二次怎么也找不到了
就是，邀请码的页面
邀请码列表：
下面还有一行小字，我想改下，咋也找不到了

**Comment by Ehco1996** [comment]
simple_settings_product.py
在文件比较下面的地方
