### ISSUE TITLE
关于ws+tls配置的问题

### ISSUE THREAD

**Issue by Gkirito** [Ehco1996/django-sspanel#304]
在配置ws+tls时，可能是由于没有参考文档，我按我目前的方式配置，发现个逻辑问题：
在django-sspanel面板配置时，端口填写10086，在v2scar的docker中会开启10086，并映射到vps的10086端口，但是配置好ws+tls之后，连接采用https，所以客户端的配置端口应该为443，可是一键导入配置中的客户端连接端口是根据编辑节点中配置的10086端口而来，但是如果修改编辑节点中的10086为443，就会导致docker中映射应该为443—>10086（如果重启v2scar），目前解决方式可以是编辑节点中保持10086，手动修改本地客户端配置的端口，将10086改成443；或者编辑节点中保持443，修改v2scar的v2ray的docker-compose中ports:
      - "10086:443"
这个目前我也不是很清楚是不是个BUG

**Comment by Ehco1996** [comment]
这应该是个bug，如果配置了ws的话应该显示的端口都是443，有时间我修一下

**Comment by Gkirito** [comment]
👌

**Comment by Ehco1996** [comment]
@Gkirito  我又想了一下，这样的隐式替换并不太好。
可以这样做，在后台配置一条转发规则，将流量从10086->443，这样客户端读取配置的时候就会读到443了

**Comment by Gkirito** [comment]
也对，可以通过转发规则转发到443，我试试

**Comment by Gkirito** [comment]
大佬没时间修的话，我可以帮忙试试，顺便学一下Django，之前都是java开发

**Comment by Ehco1996** [comment]
欢迎

**Comment by raeuz** [comment]
有 Java 版本面板, 叫 v2ray-web-manager,  我觉得它的功能很实在, 挺好的.

**Comment by Gkirito** [comment]
已修复

**Comment by Gkirito** [comment]
突然发现有人问怎么配置ws+tls，我的配置过程记录在这里了
[django-sspanel+v2scar v2ray+ws+tls](https://www.gkirito.com/airportbuild/)
