### ISSUE TITLE
在Chrome Mobile上显示滚动条的问题

### ISSUE THREAD

**Issue by limitfan** [Ehco1996/django-sspanel#31]
![django-sspanel-scrollbar-display-bug](https://user-images.githubusercontent.com/1780731/33003881-828f780c-cdf8-11e7-8f05-1bbf32d381e1.PNG)
如右侧红框中所选。
这问题也在其它地方有人同样遇到。
[Bulma issue](https://github.com/jgthms/bulma/issues/776)

**Comment by Ehco1996** [comment]
是滚动条不显示么？
在我的手机上 ios chrome 是有滚动条的
请详细描述一下

**Comment by Ehco1996** [comment]
我发现你说的问题了，
测试了一下你的css是ok的
十分感谢！
