### ISSUE TITLE
v2后端如何使用ws+tls

### ISSUE THREAD

**Issue by chengziorange** [Ehco1996/django-sspanel#313]
翻了一下issue也没看见有人提到怎么做，有点茫然。新建节点的时候并没看到证书相关的设置。是修改docker nginx的配置吗？但我的理解是后端需要有ssl证书的配置才可以ws+tls，nginx是给前端提供服务的。

**Comment by rsgdxp** [comment]
me too

**Comment by Ehco1996** [comment]
参考 #304
