### ISSUE TITLE
Docker 部署 提示 django.db.utils.OperationalError: (2005, "Unknown MySQL server host 'mysql' (-2)")

### ISSUE THREAD

**Issue by cyea** [Ehco1996/django-sspanel#317]
## docker 部署 
输入
```
docker-compose run --rm web python manage.py collectstatic --noinput
```

报错 mysql 链接不了

```
django.db.utils.OperationalError: (2005, "Unknown MySQL server host 'mysql' (-2)")
```

**Comment by Ehco1996** [comment]
可能是docker版本的问题，可以自己开一下容器之间link上了么

**Comment by t822876884** [comment]
情况1：可能是没有权限，可以先启动mysql，放开权限，然后启动其他项目
-- 启动
docker-compose up -d mysql

-- 授权 MySQL start --
	docker-compose exec mysql bash

	mysql -u root -p

	键入root密码

	grant all privileges on *.* to root@"%" identified by "yourpass" with grant option;

--授权 MySQL end --

--启动其他项目
docker-compose up -d web nginx cron
