### ISSUE TITLE
使用者列表顯示錯誤

### ISSUE THREAD

**Issue by xjxuvup1** [Ehco1996/django-sspanel#33]
使用者列表頁碼顯示錯誤

**Comment by xjxuvup1** [comment]
bug重現操作順序：用戶列表→編輯用戶資料→隨意修改一項資料→確認修改→返回用戶列表→頁碼呈現無數字狀態。

**Comment by Ehco1996** [comment]
Fixed [here](https://github.com/Ehco1996/django-sspanel/commit/4a9c6dedaecb607c37bc31d2e050ab25617e292b)
