### ISSUE TITLE
提个小小的建议

### ISSUE THREAD

**Issue by cheapssr** [Ehco1996/django-sspanel#34]
线路排序好了，，我手动弄了一遍

**Comment by cheapssr** [comment]
核心思想就是，让线路看起来整齐有序，看看怎么容易实现吧

**Comment by cheapssr** [comment]
顶帖子
顺便说下，希望在用户列表，把余额和到期日也显示出来

**Comment by cheapssr** [comment]
购买记录里面，能搜索用户就好了，可以看到每个用户的购买记录

**Comment by cheapssr** [comment]
继续顶，刚想到，搜索用户的时候，可以用端口号搜索，这样方便很多

**Comment by imMMX** [comment]
不要钱找个程序员来开发自己的系统，这小小的建议真不小啊。

**Comment by cheapssr** [comment]
。。。。自己的系统？？弄好了，只有我一个人用吗？

**Comment by imMMX** [comment]
建议此 issue 关闭 @Ehco1996

**Comment by cheapssr** [comment]
@imMMX 妨碍到你了？

**Comment by imMMX** [comment]
自行阅读  [正确的提问方式](https://github.com/Ehco1996/django-sspanel/wiki/%E6%AD%A3%E7%A1%AE%E7%9A%84%E6%8F%90%E9%97%AE%E6%96%B9%E5%BC%8F) 下次那种时间戳怎么转换的问题不要跑来 issue 这里问。

**Comment by a5234338** [comment]
@cheapssr 【。。。。自己的系统？？弄好了，只有我一个人用吗？】
你这话是不是有点问题？你有没有想过，@Ehco1996 又凭什么要给我们，给你用呢？用你的话，他自己一个人用不就好吗？

**Comment by cheapssr** [comment]
@a5234338 你想占据道德制高点，然后说别人，可以啊。制高点你站稳。
这都是个关闭的issue了，你有什么用意吗？

**Comment by a5234338** [comment]
@cheapssr 我用意？你这么想我就没办法了。没必要我特意来找你的issue。我来是看看这里有没有我当下遇到的问题，还不能说话了？随你怎么想吧

**Comment by cheapssr** [comment]
@a5234338 可以啊，你可以说话啊，么有禁止你说话的权利，你奈特我干嘛？为什么要指责我？你想说话，留言就好了，奈特我干嘛？用你的话说，你凭什么奈特我？你凭什么让我想，你提出的问题？
在发挥什么，是不是说别人几句，你心里有啥快感？

**Comment by a5234338** [comment]
@cheapssr 你赢了

**Comment by cheapssr** [comment]
@a5234338 这个没有输赢
