### ISSUE TITLE
关于网站域名设置（订阅功能）造成不能绑定多个域名

### ISSUE THREAD

**Issue by cheapssr** [Ehco1996/django-sspanel#36]
设置网站域名的话，HOST = 'http://www.xxxxxx.com/ 
就只能绑定这个域名
不能像以前一样，多个域名了
ALLOWED_HOSTS = [
    'www.xxxxxxx.com 

'
]
希望作者改一下

**Comment by Ehco1996** [comment]
可以多多个域名访问，
不止settings里要设置
nginx里也需要设置
