### ISSUE TITLE
支持vless协议

### ISSUE THREAD

**Issue by Ehco1996** [Ehco1996/django-sspanel#361]

**Comment by Gkirito** [comment]
看了一下，clash还是没支持vless，很痛苦

**Comment by Ehco1996** [comment]
问题不大，只是vless节点暂时不支持clash就好，还是可以正常用的

**Comment by xray-v2ray-ss** [comment]
给sspanel增加增加 Vless / xtls 支持
https://github.com/xray-v2ray-ss/xPanel

**Comment by Ehco1996** [comment]
暂时关闭,等下游 clash 啥时候能支持 vless 了再 reopen
