### ISSUE TITLE
部署了节点之后，发现必须使用SSR客户端才能连接到节点

### ISSUE THREAD

**Issue by threekidney** [Ehco1996/django-sspanel#37]
请问是在哪里设置使用原版SS就可以连接呢？记得前段时间安装的时候，ssr跟原版ss客户端都是可以连接到节点的，现在不行了，节点一直提示common.py:238 unsupported addrtype 69, maybe wrong password or encryption method

**Comment by Ehco1996** [comment]
使用原版ss需要将线路混淆设置成兼容模式
