### ISSUE TITLE
500 Internal Privoxy Error

### ISSUE THREAD

**Issue by steven-bin** [Ehco1996/django-sspanel#379]
**大大,我用XsHELL6在谷歌云上已经装好面板:django-sspanel,并且有开启成功,通过IP访问时提示:"500 Internal Privoxy Error
Privoxy encountered an error while processing your request:

Could not load template file no-server-data or one of its included components.

Please contact your proxy administrator.

If you are the proxy administrator, please put the required file(s)in the (confdir)/templates directory. The location of the (confdir) directory is specified in the main Privoxy config file. (It's typically the Privoxy install directory)."**

**项目的配置文件django-sspanel**

**相关截图
![微信截图_20200828114932](https://user-images.githubusercontent.com/70359631/91519241-9ec49800-e924-11ea-8891-7708087aea52.jpg)
/log**

看哪里出了问题,谢谢

**Comment by Ehco1996** [comment]
请按照isuee template来重新提
