### ISSUE TITLE
你好，我安装好后输入ip还是显示lnmp安装成功的页面

### ISSUE THREAD

**Issue by Zhenyu97cool** [Ehco1996/django-sspanel#38]
第一次动手安装这个，不太懂。求指教，不胜感激

**Comment by cheapssr** [comment]
嗯，这个小事情，就不要打扰作者了。
可以百度谷歌，各种安装教程
可以找人代搭建
作者主要精力，还是维护代码代码吧
主要是，不能添加多个域名了，不然会报错，希望修复这个
一般这类网站，多弄几个域名，防止被墙

**Comment by Ehco1996** [comment]
@Zhenyu97cool 
nginx 没设置好，可以去搜索一下对应关键词
