### ISSUE TITLE
docker提示错误

### ISSUE THREAD

**Issue by MJ5201314** [Ehco1996/django-sspanel#391]
**问题的描述**

无法启动项目

**项目的配置文件**

**如何复现**

debian9 centos7 

docker官网安装docker Engine以及docker-compose

dockerengine版本Docker version 19.03.12, build 48a66213fe
docker-compose版本 docker-compose version 1.26.2, build eefe0d31

**相关截图/log**

root@test:/www/django-sspanel# docker-compose up -d
Creating network "django-sspanel_sspanel" with the default driver
Pulling nginx (nginx:1.7.9)...
1.7.9: Pulling from library/nginx
Image docker.io/library/nginx:1.7.9 uses outdated schema1 manifest format. Please upgrade to a schema2 image for better future compatibility. More information at https://docs.docker.com/registry/spec/deprecated-schema-v1/
a3ed95caeb02: Pull complete
6f5424ebd796: Pull complete
d15444df170a: Pull complete
e83f073daa67: Pull complete
a4d93e421023: Pull complete
084adbca2647: Pull complete
c9cec474c523: Pull complete
Digest: sha256:e3456c851a152494c3e4ff5fcc26f240206abac0c9d794affb40e0714846c451
Status: Downloaded newer image for nginx:1.7.9
Creating mysql ... done
Creating redis ... done
Creating celery-worker ... error
Creating celery-worker ...
Creating web           ...

Creating celery-worker ... done
 name "/celery-worker" is already in use by container "2b5ecb133fd163564f6cd215a62347c115a19d615937aCreating web           ... done
Creating nginx         ... done

ERROR: for celery-worker  Cannot create container for service celery-worker: Conflict. The container name "/celery-worker" is already in use by container "2b5ecb133fd163564f6cd215a62347c115a19d615937a520fa273d92e78d13f2". You have to remove (or rename) that container to be able to reuse that name.
ERROR: Encountered errors while bringing up the project.

**其他信息**

**Comment by Ehco1996** [comment]
@MJ5201314 

最新的commit已经修复了，是compose写的不对

**Comment by MJ5201314** [comment]
> @ MJ5201314
> 
> 最新的commit已经修复了，是compose写的不对

好的，我再试试
