### ISSUE TITLE
配置全部通过环境变量取

### ISSUE THREAD

**Issue by Ehco1996** [Ehco1996/django-sspanel#392]

**Comment by imshunzi** [comment]
既然全部使用环境变量，为啥数据库 db name跟db port不也配置进去呢？

**Comment by Gkirito** [comment]
> 既然全部使用环境变量，为啥数据库 db name跟db port不也配置进去呢？

有道理，这样可以对接一些db服务商，下回增加一下

**Comment by imshunzi** [comment]
> > 既然全部使用环境变量，为啥数据库 db name跟db port不也配置进去呢？
> 
> 有道理，这样可以对接一些db服务商，下回增加一下

666
