### ISSUE TITLE
配置面板运行uwsgi时出错

### ISSUE THREAD

**Issue by Zecozhang** [Ehco1996/django-sspanel#40]
命令 uwsgi uwsgi.ini

打印:
[uWSGI] getting INI configuration from uwsgi.ini 
*** Starting uWSGI 2.0.15 (64bit) on [Mon Dec  4 
10:17:00 2017] ***                               
compiled with version: 4.8.5 20150623 (Red Hat 4.
8.5-16) on 04 December 2017 10:14:29             
os: Linux-3.10.0-514.26.2.el7.x86_64 #1 SMP Tue J
ul 4 15:04:05 UTC 2017                           
nodename: clickdev                               
machine: x86_64                                  
clock source: unix                               
pcre jit disabled                                
detected number of CPU cores: 1                  
current working directory: /www/wwwroot/plane/dja
ngo-sspanel                                      
writing pidfile to /tmp/django-sspanel.pid       
detected binary path: /root/.pyenv/versions/3.6.1
/envs/venv-sspanel/bin/uwsgi                     
uWSGI running as root, you can use --uid/--gid/--
chroot options                                   
*** WARNING: you are running uWSGI as root !!! (u
se the --uid flag) ***                           
chdir() to /home/www/plane/django-sspanel/       
chdir(): No such file or directory [core/uwsgi.c 
line 2591]                                       
VACUUM: pidfile removed.                         
chdir(): No such file or directory [core/uwsgi.c 
line 1613]

**Comment by Ehco1996** [comment]
项目目录配置
/home/www/plane/django-sspanel/

这里改为你自己的目录

**Comment by Zecozhang** [comment]
Sorry,我一直没意识到自己Server的起始目录不在/home
