### ISSUE TITLE
请问能把支付宝的教程，写的详细一些吗

### ISSUE THREAD

**Issue by cheapssr** [Ehco1996/django-sspanel#41]
我已经填写了appid
上传了2个文件
可是点击提交是sever 500
alipay = AliPay(
    appid=APPID,
    app_notify_url="",
    app_private_key_path=PRIVATE_KEY_PATH,
    # 支付宝的公钥，验证支付宝回传消息使用，不是你自己的公钥,
    alipay_public_key_path=PUBLIC_KEY_PATH,
    sign_type="RSA2",  # RSA 或者 RSA2
    debug=False,  # 默认False
)
这里换需要填写什么东西吗
    appid=APPID,
这个是默认不动，还是填写我的appid
    app_notify_url="",
这个填写什么，还是默认呢

**Comment by cheapssr** [comment]
还有wiki教程，应该是一个公钥一个私钥吧，wiki写的是两个公钥

**Comment by Ehco1996** [comment]
wiki里写的已经很清楚了

并没有弄混公钥和私钥
