### ISSUE TITLE
版本升级数据库migrate出现错误

### ISSUE THREAD

**Issue by jackjieYYY** [Ehco1996/django-sspanel#411]
**问题的描述**
使用的docker版本，但是和数据库分离。数据库在另外一台小鸡上面。这次前端升级到最新版本，数据库migrate时候出现错误。

**具体操作** 
删除旧版本文件夹 删除docker相关镜像。
git clone https://github.com/Ehco1996/django-sspanel.git
修改相关配置信息
docker-compose run --rm web python manage.py collectstatic --noinput
docker-compose run --rm web python manage.py migrate #出错

**项目的配置文件**
[docker-compose.yml.txt](https://github.com/Ehco1996/django-sspanel/files/5319367/docker-compose.yml.txt)

**如何复现**

**相关截图/log**
![1](https://user-images.githubusercontent.com/53422254/94949872-032ad680-0525-11eb-9aa8-9340d286bfe7.png)

**其他信息**

**Comment by Ehco1996** [comment]
mi表被squash过一次可能有点问题，需要自己fake一下

**Comment by jackjieYYY** [comment]
> mi表被squash过一次可能有点问题，需要自己fake一下

谢谢
