### ISSUE TITLE
启动失败，错误报告  No module named 'django_crontab'

### ISSUE THREAD

**Issue by jackjieYYY** [Ehco1996/django-sspanel#412]
**问题的描述**
使用2.4版的release https://github.com/Ehco1996/django-sspanel/releases/tag/2.4

命令 docker-compose run --rm web python manage.py collectstatic --noinput 后报错 No module named 'django_crontab'

**项目的配置文件**

**如何复现**
wget https://codeload.github.com/Ehco1996/django-sspanel/zip/2.4
unzip django-sspanel-2.4
cd django-sspanel-2.4
docker-compose run --rm web python manage.py collectstatic --noinput
**相关截图/log**
![G6EISJW9SRD~{4LDU`L1%TM](https://user-images.githubusercontent.com/53422254/95006221-ad058280-064d-11eb-9f20-a537242b37ec.png)

**其他信息**
docker-compose up 的话 里面是一大堆报错>.>

**Comment by Ehco1996** [comment]
依赖是因为重新打过镜像了，
我刚release了最新的代码，用2.5的relase就好了

**Comment by jackjieYYY** [comment]
> 依赖是因为重新打过镜像了，
> 我刚release了最新的代码，用2.5的relase就好了

哇哦
