### ISSUE TITLE
ss对接线路显示超时（Timeout）

### ISSUE THREAD

**Issue by xzabaibubaix** [Ehco1996/django-sspanel#414]
两台服务器一样的系统，dedicontrol的服务器，一个对接没有问题，另外一个报错，报错信息如下：
[WARNING]2020-10-10 09:40:34,976 - core.py - handle_data_received line:92: - decrypt data error:'NoneType' object has no attribute 'decrypt' remote:('123.15.15.49', 49413),type:tcp closing...
只有SS主线这个问题，V2ray对接没有出现问题，请开发者回复，谢谢！
![60Z9(G CB}A`5C$1Z9E @ 5](https://user-images.githubusercontent.com/72650682/95652083-37a02300-0b21-11eb-81f5-8484606e3b99.png)
![}3}_$X2$}H4RV(I_0(Q7$UP](https://user-images.githubusercontent.com/72650682/95652084-38d15000-0b21-11eb-976b-dcab16750c6c.png)

**Comment by Ehco1996** [comment]
@xzabaibubaix 

需要贴出有问题的节点的配置哦

就是aip_endpoint 返回的内容
