### ISSUE TITLE
总是显示掉线的bug

### ISSUE THREAD

**Issue by cheapssr** [Ehco1996/django-sspanel#42]
线路在线正常运行，可是总是显示掉线，有时候会绿，有时候不行

**Comment by cheapssr** [comment]
运行一次ss的启动命令，好一阵
过会儿，又不行了
咱能不能做个功能，把状态就显示给后台看，前台永远是在线。嘿嘿

**Comment by Ehco1996** [comment]
如果节点显示可以用，面板却显示掉线，
那一般是数据库权限的问题，
或者是ss后端的心跳包没有正确的传输

在数据后台里有一个 `节点在线记录的栏目`，
点进去看第一个记录的日志时间，
如果该日志时间和当前时间差距小于75s，那么节点就会显示在线，
如果大于75s 那就自己检查数据库/后端的设置

**Comment by cheapssr** [comment]
1512514775
1512514863
时间记录是这样子的。。看不出来啊
好吧我太笨了
重启节点服务器就好了。。

**Comment by Ehco1996** [comment]
这个是时间戳

**Comment by xjxuvup** [comment]
要看你當前時間和服務器時間阿
時間戳轉換一下, 和本地時間對比下就知道了

**Comment by imMMX** [comment]
@Ehco1996 兄弟我觉得你应该屏蔽这个人 @cheapssr 

我大概看了一下，从来只有遇到问题过来提 issue，得到答复之后就消失，没有一点积极的反馈，提出来

的功能需求也是及其自私化，类似不付钱购买就封号，金额排序等等，个人认为这样自私自利的小白奸商

没有帮助的意义，无益开源社区的发展。

**Comment by Ehco1996** [comment]
他只是觉得他的需求都是正确且普适的...
其中有些是可以做，有些我不会做的
他这些需求，怎么说呢，应该掏钱找人定制
