### ISSUE TITLE
希望增加一个管理员可以后台添加用户的功能。

### ISSUE THREAD

**Issue by ccgakki** [Ehco1996/django-sspanel#424]
**问题的描述**
后台添加用户功能，小白合用极其方便。
目前点击添加是--500.。。。
**项目的配置文件**
//

**如何复现**

**相关截图/log**
![image](https://user-images.githubusercontent.com/44969203/97653611-28672200-1a9c-11eb-8862-cd7ac289b341.png)

**其他信息**

**Comment by Ehco1996** [comment]
@ccgakki  最新代码已经可以在后台添加用户了
