### ISSUE TITLE
大佬，数据库分离 总出现的问题

### ISSUE THREAD

**Issue by ccgakki** [Ehco1996/django-sspanel#425]
**问题的描述**
docker 安装时，收集静态资源，还是创建数据库总出现
django.db.utils.OperationalError: (1045, "Access denied for user 'dj'@'172.23.0.8' (using password: YES)")
从之前的issue看，需要在production.py里写数据库配置是吗？能请问一下怎么写么。。。

**项目的配置文件**
db.py里已经填写了正确的远程数据库配置，也亦可以访问。

**如何复现**

**相关截图/log**
![image](https://user-images.githubusercontent.com/44969203/97820013-12996d00-1ce7-11eb-8d25-53a10231f7e8.png)

**其他信息**

**Comment by Gkirito** [comment]
我知道这个问题，我已经本地修复好了，等等就提交pr

**Comment by Gkirito** [comment]
问题原因是数据库还没启动完，web服务带起来了，就去连接了，即便是depends_on，docker服务不负责监控容器内的服务是否已经启动完整，所以导致数据库首次启动慢，web被带起来了，所以连接失败

**Comment by Gkirito** [comment]
刚刚没看仔细。你似乎是数据库密码问题吧

**Comment by Gkirito** [comment]
仔细看了一下，如果你的数据库时远程（我理解是不是同一个服务器上），那你连接数据库的地址是不是有问题，图片报错的172.23.0.8这个是私有地址吧

**Comment by ccgakki** [comment]
地址写在db.py里，没问题的应该，是另一个服务器的ip地址。。。就迷惑

**Comment by Ehco1996** [comment]
@ccgakki mysql开远程访问的权限了么

**Comment by ccgakki** [comment]
开了的。。。所有人 可以 访问。就很奇怪。

**Comment by ccgakki** [comment]
大概知道了 。数据库编码格式问题...
