### ISSUE TITLE
等级到期，用户仍可以用高级节点

### ISSUE THREAD

**Issue by xchensir** [Ehco1996/django-sspanel#43]
发现问题：等级时间到期用户仍可以上网；免费用户签到的流量再知道高级服务器ip的情况下也可以上网
详细：
1、刚刚注册的用户，登录后等级到期时间为注册的时间，上次使用时间为1月1日 8点；
2、购买套餐之后，等级有效期的时间按套餐所定时间添加正确，但是等级时间到期之后，用户仍可以继续使用，等级没有降到0级，高级线路信息仍可以正常显示；
3、只要免费用户（0级）有流量，知道高级服务器的ip也可以上网。

**Comment by Ehco1996** [comment]
1. 等级只针对付费用户 即 >0级别的用户
2. 等级到期的检测是每天12点的时候系统进行查询的，到期之后就不能使用所有线路
3. 面板本来就只能做一个控制显示的功能 ，通过等级筛选是否能使用是后端做的

**Comment by cheapssr** [comment]
我也遇到过这个情况，等级到期了，但是用户没有降到0级，流量也没有清空。
我是后台手动设定的到期日和流量，做测试用的，发现到期没有停止

**Comment by cheapssr** [comment]
能在用户列表页面，把每个用户的到期时间显示出来吗？这样就算么有自动停，也可以手工停的

**Comment by Ehco1996** [comment]
`python manage.py crontab add`
检查定时任务是否打开

**Comment by xchensir** [comment]
定时任务开启，等级到期之后付费用户仍可以使用。
难道是等级到期之后可以使用 12点系统进行查询之后才会停止使用吗？

**Comment by Ehco1996** [comment]
@xchensir 对的，

**Comment by MikuShare** [comment]
@Ehco1996 好像是这样的，我设置了每分钟检查一次到期，但是该到期的用户等级还是没有降级.
![qq 20180221235100](https://user-images.githubusercontent.com/25380989/36489998-4269b46e-1762-11e8-8722-ce2463b58450.png)

**Comment by Ehco1996** [comment]
是面办里显示没有降级么？
还是说降级了，但是降级了后端依旧可以连接？

如果是第二种情况，请使用最新的后端版本

**Comment by MikuShare** [comment]
@Ehco1996 都没有降级，面板里面也没有降级，后端因为没有降级所以可以继续连接。
并且我发现在SSSERVER一栏的SS账户里面直接修改用户等级是没有用的，需要跟SHADOWSOCKS一栏的用户里面的用户等级一起设置，这个时候用户等级才会生效。

**Comment by Ehco1996** [comment]
@MikuShare 
user表里的level是和shadowsocks_user 表绑定的
只修改ssserver里user表的字段，在save的时候还是会同步到原来的level

我这里的等级检测是没问题的

**Comment by MikuShare** [comment]
@Ehco1996 如果我单独修改 首页 › Shadowsocks › 用户的等级，这样等级是不会生效的，但是面板会显示修改之后的等级。必须再修改 首页 › Ssserver › SS账户的等级，这样才会生效。这样之后还是等级检测继续不管用。

**Comment by Ehco1996** [comment]
@MikuShare 等级本来就是不能单独修改的。如果计划任务成功执行了，用户的等级一定会降回0

**Comment by MikuShare** [comment]
@Ehco1996 确实是计划任务执行成功了，但是用户等级没有变动。

**Comment by MikuShare** [comment]
@Ehco1996 等级不能单独修改，也就是说等级确实需要修改两个地方是吗？

**Comment by Ehco1996** [comment]
@MikuShare 
计划任务如果执行成功了，那等级肯定会降的

等级不要需要修改，购买商品会自动增加对应的等级

**Comment by MikuShare** [comment]
@Ehco1996 我特意设置了一个商品，等级一天有效，购买之后今天这个时候等级到期，发现端口没有被移除，看定时任务的logo是有检查的，并且面板还是如下显示。
![image](https://user-images.githubusercontent.com/25380989/36627575-c2381176-197f-11e8-9458-ceffaf4cdc06.png)

**Comment by iamua** [comment]
这个问题现在已经修复了吗？

**Comment by Edwiinlai** [comment]
换个思路解决问题，本人已尝试成功重置用户等级，用户即不可使用高级节点
