### ISSUE TITLE
docker-compose 时的疑问

### ISSUE THREAD

**Issue by FToby** [Ehco1996/django-sspanel#433]
docker-compose 提示 couldn't find env file

请问下如何解决这个问题
-----------------------------------------
尝试cp .env.sample .env

然后继续进行出现 error

[root@144 django-sspanel]# docker-compose run --rm web python manage.py collectstatic --noinput
ERROR: In file ./.env: environment variable name 'port ' may not contain whitespace.

**Comment by Gkirito** [comment]
升级一下docker-compose，低版本不支持env文件有空格
