### ISSUE TITLE
想问一下 如何让v2订阅链接只有ws模式

### ISSUE THREAD

**Issue by ccgakki** [Ehco1996/django-sspanel#434]
**问题的描述**
在后台添加v2节点，填写域名和wspath 后，小火箭导入订阅链接总是会出现 勾选tls和不安全模式，然后我只是想用ws，并不想启用tls啊，不想配置证书什么的。
**项目的配置文件**

**如何复现**

**相关截图/log**

**其他信息**

**Comment by Ehco1996** [comment]
ws 和tls相关的部分是另外一个小伙伴提的pr，这部分之后可能会重构一下，
