### ISSUE TITLE
为什么会使用URLEncoded格式编写SS订阅内容？

### ISSUE THREAD

**Issue by Okeyja** [Ehco1996/django-sspanel#436]
URLEncoded会导致ElectronSSR的订阅Decode不了哦。

**Comment by Ehco1996** [comment]
这个是ss官方的spec里的要求哦

具体原因是remark字段里有可能会有中文，这里应该向ElectronSSR提issue让客户端去适配

**Comment by Okeyja** [comment]
ElectronSSR 现在已经没有人维护了，哭。我看我要不要捡一下。
