### ISSUE TITLE
面板登录时返回500错误 debug显示User has no ss_user

### ISSUE THREAD

**Issue by HelicalH** [Ehco1996/django-sspanel#45]
dalao你好，请帮忙看一下谢谢。
Environment:

Request Method: POST
Request URL: http://5.39.57.xx/login/

Django Version: 1.11.4
Python Version: 3.6.3
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django_crontab',
 'shadowsocks',
 'ssserver']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']

Traceback:

File "/root/.pyenv/versions/3.6.3/envs/venv-sspanel/lib/python3.6/site-packages/django/core/handlers/exception.py" in inner
  41.             response = get_response(request)

File "/root/.pyenv/versions/3.6.3/envs/venv-sspanel/lib/python3.6/site-packages/django/core/handlers/base.py" in _get_response
  187.                 response = self.process_exception_by_middleware(e, request)

File "/root/.pyenv/versions/3.6.3/envs/venv-sspanel/lib/python3.6/site-packages/django/core/handlers/base.py" in _get_response
  185.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "./shadowsocks/views.py" in Login_view
  144.                 remain_traffic = 100 - eval(user.ss_user.get_used_percentage())

File "/root/.pyenv/versions/3.6.3/envs/venv-sspanel/lib/python3.6/site-packages/django/db/models/fields/related_descriptors.py" in __get__
  407.                     self.related.get_accessor_name()

Exception Type: RelatedObjectDoesNotExist at /login/
Exception Value: User has no ss_user.

数据库表 sspanel 中 shadowsocks_user 里面添加进用户可以查到
![image](https://user-images.githubusercontent.com/34448395/34070236-492edfb2-e29d-11e7-986f-a36358f0c132.png)
也显示登录时的时间。

后端./tail.sh
db_transfer.py:391 no user in db

**Comment by Ehco1996** [comment]
仔细看安装wiki的最后一步，需要进后台绑定一下ss_user

**Comment by HelicalH** [comment]
运行项目
    $ uwsgi uwsgi.ini
ok，尝试访问你的域名吧！
PS：管理员**账号登录之后**，先得去django后台绑定一下 **<<=我是管理员账号用python manage.py createsuperuser创建后第一次登录不上啊？**
只有管理员才需要这个步骤，正常通过注册生成的用户会自动绑定的
具体步骤：
登录管理账号 **<<=这里报错错的啊，我理解是第一次登录以后去面板里面绑定，但是我是第一次登录登录不上啊。是我的理解有偏差吗？麻烦请大佬指教？感谢。**
进入django后台
选择ssserver应用下的ss账户
点击右上角的添加账号
绑定自己的管理员账号

另外如果故意输错误的账号密码不会报错，会正常提示账号密码错误。

**Comment by Ehco1996** [comment]
@HelicalH  可以输入你的域名+/admin 进入后台绑定一下账户，可能是我之后更新的版本，出现了问题

第二个问题我没太明白你的意思

**Comment by HelicalH** [comment]
问题解决了{开心}，我一直以为我部署过程哪里错了搞了三天，输入 **http://域名/admin** 可以绑定，非常感谢大佬指点～第二个那个不是问题，是解释一下情况。

**Comment by a5234338** [comment]
你这情况跟我一样一样的，我也郁闷了好几天，还是多谢【lala.im】大神帮忙解决的
