### ISSUE TITLE
如何重新加载simple_setting_product.py

### ISSUE THREAD

**Issue by WYH233** [Ehco1996/django-sspanel#46]
修改了simple_setting_product.py后
如何应用？保存后没有实施

**Comment by Ehco1996** [comment]
重启应用

**Comment by WYH233** [comment]
uwsgi uwsgi.ini
执行这个语句后
显示IP地址被占用

**Comment by HelicalH** [comment]
重起电脑

**Comment by Ehco1996** [comment]
可以这样重启uwsgi

`uwsgi --reload  /tmp/django-sspanel.pid`
