### ISSUE TITLE
是我装环境是缺少包了吗 

### ISSUE THREAD

**Issue by 19950520** [Ehco1996/django-sspanel#48]
也是centos 7

![image](https://user-images.githubusercontent.com/13502844/34144605-413f8d60-e4cd-11e7-8900-31180c8984ac.png)

![image](https://user-images.githubusercontent.com/13502844/34144529-df3ae7fe-e4cc-11e7-9e6b-a5ac78e21cb6.png)

**Comment by Ehco1996** [comment]
好像是配置出错了
请把 simply_settings_product.py 贴上来
注意自己的隐私信息！

**Comment by 19950520** [comment]
如图 
![image](https://user-images.githubusercontent.com/13502844/34158495-a28134ec-e500-11e7-8fde-f3e65544946e.png)

**Comment by Ehco1996** [comment]
缺少了 

# 用户能生成的邀请码数量
INVITE_NUM = 5

这个字段
