### ISSUE TITLE
panel后台修改用户的地方无法直接修改用户密码

### ISSUE THREAD

**Issue by moranno** [Ehco1996/django-sspanel#489]
panel后台：首页 / 面板配置/ 用户/修改用户 下：

显示的密码是加密过后的文本，类似这样：pbkdf2_sha256$4556420$xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

如果输入明文密码为用户修改密码，无法修改。必须输入加密后端字符串才能修改，希望改进为可以直接输入明文密码。

**Comment by Gkirito** [comment]
建议开通邮箱，让用户忘记密码操作
