### ISSUE TITLE
get_last_use_time

### ISSUE THREAD

**Issue by nnfish** [Ehco1996/django-sspanel#5]
Request Method: | GET
-- | --
http://localhost:8000/users/userinfo/
1.11.4
OSError
[Errno 22] Invalid argument
D:\Python\Github\django-sspanel\ssserver\models.py in get_last_use_time, line 112
C:\Python36\python.exe
3.6.1

**Comment by Ehco1996** [comment]
@nnfish 

**please git pull to the latest version.**

if the error still 

you can try these setps

`python manage.py test`

if  it out errors , fix it with error introduction

if it through the test,

maybe it is your database problem,

run 
`python manage.py makemigrations `
`python manage.py migrate `
