### ISSUE TITLE
捐赠金额bug？

### ISSUE THREAD

**Issue by HelicalH** [Ehco1996/django-sspanel#50]
捐赠付费=》输入金额=》提交=》生成1号二维码=》不支付直接再次点击提交=》二维码不改变？=》这时候扫描1号二维码=》钱到支付宝帐，网站查询为未支付
![image](https://user-images.githubusercontent.com/34448395/34242508-bf392aac-e656-11e7-90a8-19776c0dd291.png)
1号二维码。
![image](https://user-images.githubusercontent.com/34448395/34242531-d0dd6fca-e656-11e7-8c63-a56027038ed0.png)
改变金额再次点击提交，二维码没有改变。
![image](https://user-images.githubusercontent.com/34448395/34242570-0d79df54-e657-11e7-8f88-4d31bf5094ef.png)
在查询后的页面提交金额，刷不出二维码

**Comment by Ehco1996** [comment]
这是个问题，记录下了
谢谢告知。
我准备这样修复：

第一次提交订单之后，将提交的按钮变为灰色
这样就不存在多次提交的问题了

**Comment by HelicalH** [comment]
嗯，这中解决办法让我很受启发，哈哈，简单实用。

**Comment by Ehco1996** [comment]
[Fixed](https://github.com/Ehco1996/django-sspanel/tree/f23bf08e19c9eb5b8969f167bf544c49cedad010)
