### ISSUE TITLE
docker 国内某些服务器build问题

### ISSUE THREAD

**Issue by LunacyZeus** [Ehco1996/django-sspanel#503]
**问题的描述**
在天翼云build docker的时候发现pip下载数据很慢 加了几行更换pip源的代码改进了
**项目的配置文件**
无

**如何复现**
无

**相关截图/log**
无

**其他信息**
`FROM python:3.8-alpine as base

LABEL Name=django-sspanel

ENV CRYPTOGRAPHY_DONT_BUILD_RUST=1

COPY requirements.txt /tmp/requirements.txt
#修改alpinelinux镜像源
RUN set -eux && sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories
RUN apk add --update --no-cache mariadb-connector-c-dev tzdata \
	&& apk add --no-cache --virtual .build-deps mariadb-dev gcc musl-dev libffi-dev make \
	# TODO workaround start
	#修改pip为国内源
	&& pip install --no-cache-dir pqi \
	&& pqi use aliyun \
	&& pip install --no-cache-dir -r /tmp/requirements.txt \
	# TODO workaround end
	&& apk del .build-deps \
	&& cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
	&& echo "Asia/Shanghai" > /etc/timezone`

**Comment by Gkirito** [comment]
ehco大佬有build好的runtime镜像

**Comment by Ehco1996** [comment]
@LunacyZeus 欢迎提个pr
