### ISSUE TITLE
支付界面自动轮训？

### ISSUE THREAD

**Issue by Ehco1996** [Ehco1996/django-sspanel#508]

**Comment by Gkirito** [comment]
轮训接口吗，会不会被训坏

**Comment by Ehco1996** [comment]
> 轮训接口吗，会不会被训坏

不会的，轮训其实这个场景下的标准做法 @Gkirito

**Comment by Gkirito** [comment]
> > 轮训接口吗，会不会被训坏
> 
> 不会的，轮训其实这个场景下的标准做法 @Gkirito

是不是可以上个websocket，轮询出结果后，通知前端充值完成

**Comment by Ehco1996** [comment]
这样需要部署websocket服务器,简单场景下没必要增加复杂度了

Gkirito ***@***.***> 于2021年4月23日周五 下午1:21写道：

**Comment by Gkirito** [comment]
Hh， 好的
