### ISSUE TITLE
节点二维码

### ISSUE THREAD

**Issue by a5234338** [Ehco1996/django-sspanel#52]
同时显示ss和ssr的二维码是不是有点不科学，总要找另一个程序挡住其中一个二维码再用客户端扫描屏幕

**Comment by xjxuvup** [comment]
请鼠标右键点击图片, 另外开起视窗显示图片

**Comment by a5234338** [comment]
抱歉，也许是我没说清楚。在电脑上使用ssr扫描二维码功能，当屏幕上同时有2个二维码时，无法自主选择性的扫描其中一个二维码。

建议解决方法：ss，ssr的二维码分开显示

另外，我发现我站点的ssr二维码用ssr（win版）扫描无法正确导入，ss二维码却没问题。再试了一下站长的站点，ssr二维码可以正确识别。
猜测：也许跟ssr参数有关，以下是我使用的ssr参数。

加密方式: | none
协议(ss版客户端可不填写): | auth_chain_a
混淆(ss版客户端可不填写): | plain

**Comment by xjxuvup** [comment]
分开显示你自己点击右键新开视窗就能显示了

**Comment by a5234338** [comment]
这倒是个办法

**Comment by Ehco1996** [comment]
不能自动识别是因为你的win客户端不支持auth_china_a 的协议

关于二维码的位置我会考虑的，我大概明白你的意思了，你是说电脑客户端直接扫描屏幕上的二维码，有两个扫不出来对吧？

我一直用的是路由器，和手机app。基本不用电脑版本的客户端 所有一直没发现你的问题

**Comment by a5234338** [comment]
二维码是这个意思。

我win客户端支持auth_china_a协议的，回去看下版本告诉你。

**Comment by a5234338** [comment]
@Ehco1996 测试win版ssr（ShadowsocksR-dotnet4.0/2.0）2个版本，都无法通过识别节点二维码的方式来导入配置（ios小火箭可以正常识别），同时测试其它机场相同配置的ssr可以正常识别导入配置。

**Comment by Ehco1996** [comment]
我二维码编码方式是按照ssr的要求来的
如果小火箭能识别 其他客户端不能识别的话

要么是小火箭做了兼容处理
要么是其他网站的链接做了兼容处理

但是我不知道其他网站的规则是什么
所有我也不知道怎么修改

**Comment by Ehco1996** [comment]
@a5234338 
最新的版本修复了
检查出来是我写的一个bug

**Comment by a5234338** [comment]
还有，上面说的ss和ssr2个二维码没分开啊

**Comment by SSR6** [comment]
各位大佬，有个问题想请教下，为什么节点的二维码安卓的手机、Windows能扫出来，IOS的就不行，以前可以的，IOS扫码后提示无效的配置 URL
