### ISSUE TITLE
关于API_INTERFACE

### ISSUE THREAD

**Issue by a5234338** [Ehco1996/django-sspanel#53]
作者您好，请问这个API_INTERFACE在使用上都有什么区别？都没看到有帖子解释这个的，我主要想知道sspanelv2,sspanelv3ssr,legendsockssr这几个。您wiki介绍中用的是sspanelv3ssr，我看别的帖子前后分别用了另外2种。

**Comment by Ehco1996** [comment]
操作数据库的逻辑不一样

**Comment by a5234338** [comment]
谢谢！不过，能不能辛苦您简单说一下使用上或者说功能上的意义呢？
