### ISSUE TITLE
执行docker-compose run --rm web python manage.py migrate报错

### ISSUE THREAD

**Issue by PengsongAndroid** [Ehco1996/django-sspanel#532]
执行创建数据库表命令报错

docker-compose run --rm web python manage.py migrate
Creating django-sspanel_web_run ... done
SystemCheckError: System check identified some issues:
ERRORS:
proxy.UserTrafficLog: (fields.E180) MySQL does not support JSONFields.

**Comment by Ehco1996** [comment]
@PengsongAndroid 

不是 bug 哦，mysql 版本需要 5.7 以上

方便的话可以提个 pr ，在 readme 里体现一下

**Comment by PengsongAndroid** [comment]
> @PengsongAndroid
> 
> 不是 bug 哦，mysql 版本需要 5.7 以上
> 
> 方便的话可以提个 pr ，在 readme 里体现一下

好的 谢谢大佬

**Comment by NoviceLevel** [comment]
5.7包含吗
