### ISSUE TITLE
配置V2ray节点没有对接地址

### ISSUE THREAD

**Issue by PengsongAndroid** [Ehco1996/django-sspanel#535]
请问一下，这样配置是哪里有问题，为什么看不到对接的地址
![1804dde262bd028683fca4a1f89cb86](https://user-images.githubusercontent.com/11801876/119762264-f3ab3400-bedf-11eb-9628-432b6e06debf.png)
![d4d26f8c5b6555b471481c82622c681](https://user-images.githubusercontent.com/11801876/119762266-f4dc6100-bedf-11eb-848f-f77edf5dc071.png)

**Comment by Ehco1996** [comment]
#459

**Comment by PengsongAndroid** [comment]
> #459

意思是目前master分支才支持嘛
