### ISSUE TITLE
端口限制问题

### ISSUE THREAD

**Issue by yokiy0828** [Ehco1996/django-sspanel#54]
请问端口范围怎么限制？

**Comment by Ehco1996** [comment]
配置文件里就有

**Comment by yokiy0828** [comment]
没看到呀？哪个配置文件？

**Comment by Ehco1996** [comment]
simple_settings_product.py

**Comment by yokiy0828** [comment]
没有呢？是不是忘记写了？我是说后端开通用户端口段控制。

**Comment by Ehco1996** [comment]
@yokiy0828 
我居然真的忘记添加了，抱歉。刚补上去了：
[fix](https://github.com/Ehco1996/django-sspanel/commit/7a066134c9348ed67d583a26e5863987d1a3e7aa)

**Comment by yokiy0828** [comment]
只有开始端口是吗？START_PORT  = 1024   创建是随机创建还是按顺序创建？

**Comment by Ehco1996** [comment]
按顺序的，可以看看shadowsock/views.py 里的register这个函数

**Comment by yokiy0828** [comment]
好的，谢谢。
