### ISSUE TITLE
执行docker-compose run --rm web python manage.py migrate

### ISSUE THREAD

**Issue by NoviceLevel** [Ehco1996/django-sspanel#545]
Starting redis ... 
Starting mysql ... done
SystemCheckError: System check identified some issues:

ERRORS:
proxy.UserTrafficLog: (fields.E180) MySQL does not support JSONFields.

**Comment by NoviceLevel** [comment]
mysql  Ver 8.0.25 for Linux on x86_64 (MySQL Community Server - GPL)

**Comment by NoviceLevel** [comment]
我使用了生日版成功，不知最新拉取有什么问题，

**Comment by Ehco1996** [comment]
#532
