### ISSUE TITLE
作者你好！给个建议：账号和充值码问题

### ISSUE THREAD

**Issue by 3494024534** [Ehco1996/django-sspanel#55]
之前一直用魔改v3，发现很多不方便的操作，
偶然发现你的流控，感觉不错，
但是，能否增加以下账号和充值码功能，
1.批量生成账号，登陆进平台，自动激活时间
2.充值码能否批量生成
最后一个建议
能否延用魔改v3的一键插入节点，这样客户操作简单

**Comment by Ehco1996** [comment]
1 批量生成账号？ ？？？有什么用？？
2 充值码支持批量生成
3 一键导入是？ ssr订阅么？

**Comment by 3494024534** [comment]
你好！
批量生成带使用时间账号，登陆官网激活，是很有用处的，
简单说明下，我近一年淘宝和自动发卡网销售遇到的问题，
1.顾客从注册到使用大概要20分钟时间，注册时间能占到10分钟左右，中间还要客服指导（作为卖家的我们都觉得注册很简单，但是就是有大部分客户都需要指导，是不是觉得很不可思议..........但事实就是这样很无奈）
2.一键导入就是 gui-config 这个文件，要是有几十个节点以上，一条条配置是很麻烦的
ssr订阅可用可不用，订阅地址里的域名大概2~3个月就失效，还不如直接导入

**Comment by 3494024534** [comment]
![image](https://user-images.githubusercontent.com/32893207/34405294-7f47b07a-ebed-11e7-808b-e5f25e5f709c.png)
这样的批量导入

**Comment by Ehco1996** [comment]
自动注册的话，不算是普遍需求，单独为你做的话 有点那啥对吧？

一键导入的功能好像还挺好的，记录下了，下次会做的

**Comment by Ehco1996** [comment]
导出配置json [here](https://github.com/Ehco1996/django-sspanel/commit/8a676c0a37c640cbc174c9fc9328bc90124e6e6c)
