### ISSUE TITLE
Translate in english

### ISSUE THREAD

**Issue by ghost** [Ehco1996/django-sspanel#557]
Hi, how much will need to donate, to translate django-sspanel in English language?

**Comment by Ehco1996** [comment]
@connected201 

now, there is lot's of Chinese hard code  , I would like to know why you need the English version in

i18in is a tough work for me, a donation of $500 would allow help me to start doing this work

**Comment by ghost** [comment]
hi, give bitcoin address, i will transfer 500$ to translate in english language.

**Comment by Ehco1996** [comment]
> hi, give bitcoin address, i will transfer 500$ to translate in english language.

oh thanks!  `0xB094088E04b8DA7157B4D7a4715619A267D7D106`

**Comment by ghost** [comment]
This is not bitcoin address!

also, how much time will need to translate?(~)

**Comment by Ehco1996** [comment]
> This is not bitcoin address!

oh sorry, i am not familiar with these things, btc address is `32CbVBn46ZRFCcXdWcTFwuWh7daoUgibGs`

> also, how much time will need to translate?(~)

maybe one month is enough , can't give you a  time

**Comment by Ehco1996** [comment]
reopened this

**Comment by ghost** [comment]
hi again, sorry for long delay, give me new bitcoin address! i will send 500$

**Comment by ghost** [comment]
also, please add option in frontend to select interface language. for future to have option translate front with another language config.

**Comment by Ehco1996** [comment]
> also, please add option in frontend to select interface language. for future to have option translate front with another language config.

`0xB094088E04b8DA7157B4D7a4715619A267D7D106` this is USDT address i don't want btc

**Comment by mijingduI** [comment]
哈哈哈 去年的500u的btc现在得变成200u
