### ISSUE TITLE
在.env中，Alipay=False以后，celery相关的image又起不来了；

### ISSUE THREAD

**Issue by rogolezhou** [Ehco1996/django-sspanel#560]
celery-beat     sh ./wait-for-it.sh mysql: ...   Restarting                                            
celery-worker   sh ./wait-for-it.sh mysql: ...   Restarting

**Comment by Ehco1996** [comment]
需要提供对应容器的日志

**Comment by KelthuzadC** [comment]
https://github.com/Ehco1996/django-sspanel/blob/c9e45dba9412fd823dc189f6b6edbbbbf56c1043/Makefile#L1
