### ISSUE TITLE
关于购买流程，邀请，返利的相关建议

### ISSUE THREAD

**Issue by rogolezhou** [Ehco1996/django-sspanel#561]
现在的购买流程是，支付宝付款，获取充值码，填入充值码，增加账户余额，使用余额购买相关的商品；

由于可能会由于种种原因，如果站长需要用自行生成充值码，到站外销售充值码，那么使用充值码以后，就不会有购买记录；返利效果就没有办法实现；

是不是可以让返利的效果，从充值码开始；邀请者根据被邀请者的第一个充值码充值的金额，生成返利记录，完成返利操作；这样会比较方便；

**Comment by Ehco1996** [comment]
通过支付宝支付的话不需要手动填充值码，会自动充值

**Comment by Ehco1996** [comment]
not on roadamp
