### ISSUE TITLE
面板部署求教

### ISSUE THREAD

**Issue by zoenreo** [Ehco1996/django-sspanel#59]
作者大大：
       我是全程按照部署教程部署的，测试服务器运行的时候也没有报错，但是在最后一步执行运行服务器的指令之后得到如下结果：
[uWSGI] getting INI configuration from uwsgi.ini
*** Starting uWSGI 2.0.15 (64bit) on [Sun Dec 31 02:05:28 2017] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-16) on 31 December 2017 01:36:09
os: Linux-3.10.0-514.2.2.el7.x86_64 #1 SMP Tue Dec 6 23:06:41 UTC 2016
nodename: Zoo
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /home/www/django-sspanel
writing pidfile to /tmp/django-sspanel.pid
detected binary path: /root/.pyenv/versions/3.6.1/envs/venv-sspanel/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) ***
chdir() to /home/www/django-sspanel/
your processes number limit is 65535
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8080 fd 3
Python version: 3.6.1 (default, Dec 31 2017, 01:18:39)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x2630200
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145536 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x2630200 pid: 3953 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 3953)
spawned uWSGI worker 1 (pid: 3998, cores: 1)

看上去貌似没问题，但是我访问域名以后得到的是lnmp的默认页面，加:8080提示服务器拒绝了我们的连接请求，请问我是哪里做错了吗？还是配置不对？

**Comment by Ehco1996** [comment]
贴出你的 nigix配置文件

**Comment by zoenreo** [comment]
非常感谢您的回复，已经配置好了，是域名解析的问题，谢谢，麻烦了
