### ISSUE TITLE
ImportError: cannot import name 'AliPay'

### ISSUE THREAD

**Issue by r0liang** [Ehco1996/django-sspanel#6]
到python manage.py migrate步骤提示ImportError: cannot import name 'AliPay'，自行pip install alipay后无果，故讨教下。

另pip install -r requirements.txt在centos 7下很大几率会无法正确安装mysqlclient，需要先行
yum install python36u python36u-devel
yum install gcc mariadb-devel
pip3 install mysqlclient

否则Python很大几率报错（我一路报错着来

另推荐一个一键SSL脚本，毕竟这种东西嘛（滑稽
https://www.v2ex.com/t/383032

**Comment by Ehco1996** [comment]
@r0liang 
这个问题需要安装 支付宝sdk：

`pip install python-alipay-sdk --upgrade`

回头我重新整理一下安装流程和requierments。

另外SSL现在是一定必要的了么？

**Comment by r0liang** [comment]
防劫持罢了，这个脚本比较万能，所以推荐一下
thanks~

**Comment by r0liang** [comment]
到最后一步仍然出错，麻烦大大帮看一下原因为何，尝试过运行的时候添加--chroot  -uid  --gid
 : (   实在抱歉又打扰了，uwsgi uwsgi.ini时候报错，不知何解

[root@FY-20170821221110 django-sspanel]# uwsgi uwsgi.ini
[uWSGI] getting INI configuration from uwsgi.ini
*** Starting uWSGI 2.0.15 (64bit) on [Tue Aug 22 11:16:05 2017] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-11) on 22 August 2017 01:26:33
os: Linux-3.10.0-514.26.2.el7.x86_64 #1 SMP Tue Jul 4 15:04:05 UTC 2017
nodename: FY-20170821221110
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 2
current working directory: /home/www/django_sspanel/django-sspanel
writing pidfile to /tmp/django-sspanel
detected binary path: /root/.pyenv/versions/3.6.1/envs/venv-sspanel/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) ***
chdir() to /home/www/django-sspanel/
chdir(): No such file or directory [core/uwsgi.c line 2591]
VACUUM: pidfile removed.
chdir(): No such file or directory [core/uwsgi.c line 1613]

**Comment by r0liang** [comment]
chdir(): No such file or directory [core/uwsgi.c line 2591]
chdir(): No such file or directory [core/uwsgi.c line 1613]
大大在目录下位置记错文件名了，已经自己修改过来了

**Comment by r0liang** [comment]
一切就绪后访问ip返回Bad Request (400)，绑定域名后仍然如此，此时已经全部配置文件中错误的目录修改过来，无果

**Comment by Ehco1996** [comment]
检查 /home/www/project 权限
如果是通过lnmp安装包安装的，直接访问ip应该是lnmp的index界面。
如果不是，那一般是nginx配置出错。

如果还是不行 
贴上的你的nginx 和uwsig的配置文件。

**Comment by r0liang** [comment]
```
[uwsgi]

# variables
projectname = django-sspanel
projectdomain = 's.q1et.com'
base = /home/www/django_sspanel/django-sspanel

# config
chdir= /home/www/django_sspanel/django-sspanel
plungins = python
socket = 127.0.0.1:8080
module = django_sspanel.wsgi:application
pidfile = /tmp/django-sspanel
master = True
vacuum = True
```
uwsig配置如上

`
server
    {
        listen 80;
        server_name s.q1et.com;
        root  /home/www/django_sspanel/django-sspanel;

    location /media  {
        alias /home/www/django_sspanel/django-sspanel/django_sspanel;  # your Django project's media files - amend as required
        }

        location /static
        {
        alias  /home/www/django_sspanel/django-sspanel/static; #静态文件地址，js/css
        expires  12h;
        }

        location /
        {
        include uwsgi_params;
        uwsgi_pass 127.0.0.1:8080;
        }

    }

`
nginx配置如上

感谢回复

**Comment by Ehco1996** [comment]
这样看，我也看不出什么大问题，

有可能是 django-sspanel 之间的连接符，
意思就是项目名 不要用 _ 连接 ,
也有可能是路径太深了。
你先测试一下是不是nginx配置出错了吧

**Comment by r0liang** [comment]
OK，已经搭建完毕，感谢！

**Comment by r0liang** [comment]
非常抱歉再次打扰，对于搭建完毕后SSR该如何安装对接方面，之前的sspanel都有成熟的一键对接，对此尚有疑惑，不知如何对接，求大大解答一下

**Comment by Ehco1996** [comment]
https://github.com/Ehco1996/django-sspanel/wiki
