### ISSUE TITLE
关于数据库迁移文件

### ISSUE THREAD

**Issue by qiqizjl** [Ehco1996/django-sspanel#61]
不知道为什么migrate文件每次都在删除 增加

能否不删除这个文件 如果一旦删除 我跨版本更新的时候 数据库字段会直接缺失  因为migrate是根据文件名称和数据库里面记录的迁移log来确定是否迁移的 您每次删文件我们在跨版本的时候不会加上您删除文件的字段 导致服务挂了

**Comment by Ehco1996** [comment]
我是定期会把migrations文件全部清空一次的
这样全新安装的时候就方便点

你这样说好像也有道理，那我以后就留两份好了

**Comment by qiqizjl** [comment]
其实没必要定期清空啊 其实文件多了 也是在安装的时候执行的时间长了点而已 而且这个时间可以忽略不计 本身数据库执行插入字段/表是很快 完全没必要定时清空
