### ISSUE TITLE
docker-compose.yml 中的nginx版本配置应该是1.20.1 or lastest 而不是1.7.9

### ISSUE THREAD

**Issue by couldntaccept** [Ehco1996/django-sspanel#611]
**问题的描述**
./docker-compose.yml 中的nginx版本配置应该是1.20.1 or lastest 而不是1.7.9
**项目的配置文件**
./docker-compose.yml
**如何复现**
1. 按照教程一步一步走 不改变.env 和.configs/nginx/nginx.example.conf 中的任何设置
2. docker-compose ps
**相关截图/log**
![image](https://user-images.githubusercontent.com/42738714/147471757-718c1e7d-935c-400b-b3e7-cd5f84026de7.png)

**Comment by Ehco1996** [comment]
@couldntaccept 可以提个 pr 修改一下么

**Comment by couldntaccept** [comment]
好滴

**Comment by couldntaccept** [comment]
俺没有access permission😭
![image](https://user-images.githubusercontent.com/42738714/147524729-b2d4ddcd-547b-4ee0-9992-e121bc978446.png)

**Comment by Ehco1996** [comment]
你需要先登录

**Comment by couldntaccept** [comment]
我登录啦
![image](https://user-images.githubusercontent.com/42738714/147526777-d5378ef7-d0d5-482e-9d2f-befc98224abd.png)

**Comment by couldntaccept** [comment]
我应该是登录了的 我把这个repo成功clone下来了 并且我也可以commit自己的repo
（sry啊 这是我第一次提交别人的pr 不太熟悉hhh）

**Comment by couldntaccept** [comment]
啊啊 我发现了 我sign out 又sign in了
现在显示这个
![image](https://user-images.githubusercontent.com/42738714/147527187-643d5810-0c66-429b-b2a9-e7b9d8dab326.png)

**Comment by Ehco1996** [comment]
@couldntaccept  可以学习一下怎么在 github 提 PR https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request

加油 你就快成功了！

**Comment by couldntaccept** [comment]
谢谢大佬的耐心指导！
PR在这里 :^)
https://github.com/Ehco1996/django-sspanel/pull/614
