### ISSUE TITLE
目前最新版能够关闭邀请码注册吗？或者一个邀请码可以多次使用

### ISSUE THREAD

**Issue by ghost** [Ehco1996/django-sspanel#619]
RT

**Comment by Ehco1996** [comment]
每个用户有个邀请链接，那个是可以重复使用的

**Comment by ghost** [comment]
看到了，谢谢。另外问一下，能不能某个节点只能一个或多个用户看到和使用，其他人看不到

**Comment by Ehco1996** [comment]
> 看到了，谢谢。另外问一下，能不能某个节点只能一个或多个用户看到和使用，其他人看不到

不能，节点目前的实现之和等级绑定
