### ISSUE TITLE
自定义加密方式和协议

### ISSUE THREAD

**Issue by ourpurple** [Ehco1996/django-sspanel#62]
#修改models.py增加了chaochao-ietf的加密方式和auth_chain_b的混淆协议，后端正常，前端大部分也正常，但是在节点页面显示不了新添加的协议和加密方式，如何修改解决？
![sshot-2](https://user-images.githubusercontent.com/27411933/34595127-690fae56-f210-11e7-9423-07a1d5901343.jpg)
![sshot-3](https://user-images.githubusercontent.com/27411933/34595151-936de686-f210-11e7-802f-4d7090b26645.jpg)

**Comment by Ehco1996** [comment]
Fix [here](https://github.com/Ehco1996/django-sspanel/commit/ce4ca9407720fb4456f040e69486369af655fc94)

**Comment by ourpurple** [comment]
在节点显示页面还是不能正确的显示用户个人的加密方式 协议和混淆（目前显示的都是节点在后台默认的加密方式协议和混淆） ，生成的ssr链接和订阅 都是后台节点默认的加密方式 协议 混淆

**Comment by Ehco1996** [comment]
节点需要将自定义加密打开才能显示自定义加密。

其他的没懂你意思，最好附上图片

**Comment by ourpurple** [comment]
节点需要将自定义加密打开才能显示自定义加密。   这个以前不知道，现在好了。。

但是如果自定义加密关闭的话，用户在节点编辑的界面还有权限调整加密方式，在userinfo/ 页面可以看到自定义的加密信息（连接信息里），但在nodeinfo界面就不显示自定义的加密（无论用户怎么调整，都只显示默认）

**Comment by Ehco1996** [comment]
这个逻辑没问题

用户中心里只能看到自己设置的加密方式

节点列表里的配置信息才是真正可以使用的
