### ISSUE TITLE
节点名称中文乱码

### ISSUE THREAD

**Issue by dymasch** [Ehco1996/django-sspanel#649]
**问题的描述**
使用potatso lite添加ss订阅，中文乱码

**相关截图/log**
![IMG_BF374770B5AA-1](https://user-images.githubusercontent.com/61868827/158335694-74e88d83-f0bc-48a4-8ca6-342bd649f77b.jpeg)

**Comment by Ehco1996** [comment]
需要订阅连接，另外这大概率是客户端的问题，你可以用是他客户端试试

**Comment by dymasch** [comment]
> 需要订阅连接，另外这大概率是客户端的问题，你可以用是他客户端试试

嗯，只有potatso会这样，用小水滴和小火箭正常
