### ISSUE TITLE
ehcov1.js提示病毒报错

### ISSUE THREAD

**Issue by JoeJoeyMa** [Ehco1996/django-sspanel#67]
win10自动查杀提示木马报错
django-sspanel-master.zip|https://codeload.github.com/Ehco1996/django-sspanel/zip/master|chrome.exe

具体位置
django-sspanel-master.zip->django-sspanel-master/shadowsocks/static/sspanel/js/ehcov1.js
查了源码也不知道什么情况。不知道是win10问题还是个案。

**Comment by Ehco1996** [comment]
误杀了，
这个js里面都是一些操作dom的脚本而已
