### ISSUE TITLE
有没有非docker版本？？

### ISSUE THREAD

**Issue by dingmengcm** [Ehco1996/django-sspanel#676]
有没有非docker版本？宝塔下或者其他搭建的lnmp环境下的都行，实在不喜欢docker ，不好操作！

**Comment by oh-hell** [comment]
我也觉得，为什么把之前的面板安装教程萌新版删了？

**Comment by Ehco1996** [comment]
因为人力不足，没办法维护多份教程，抱歉

**Comment by LQY96** [comment]
> 我也觉得，为什么把之前的面板安装教程萌新版删了？

现在这教程详细程度！还不够萌新啊！
