### ISSUE TITLE
发现一个小BUG

### ISSUE THREAD

**Issue by HelicalH** [Ehco1996/django-sspanel#68]
后台用户列表界面搜索用户以后点翻页报500错误
ValueError at /backend/user/search/
Cannot use None as a query value
Request Method:	GET
Request URL:	http://192.168.1.112/backend/user/search/?page=
Django Version:	2.0
Exception Type:	ValueError
Exception Value:	
Cannot use None as a query value

**Comment by Ehco1996** [comment]
dev 分支已经修复了
