### ISSUE TITLE
数据后台无法跳转

### ISSUE THREAD

**Issue by a807966224** [Ehco1996/django-sspanel#717]
**问题的描述**
我已经把页面功能启动来了，整体登录也OK，但是在看后端对接教程的时候，发现数据后台无法跳转，我看了代码里也没有在后台跳转处写跳转链接，包括html代码里也没有数据后台的添加SS链接等功能
**项目的配置文件**

**如何复现**

**相关截图/log**
![image](https://user-images.githubusercontent.com/13774826/188256622-b121788d-735c-4632-aa39-0f76697047ac.png)
![image](https://user-images.githubusercontent.com/13774826/188256636-bf379800-272d-46b2-be2e-2cc407bcbf62.png)

**其他信息**

**Comment by a807966224** [comment]
我整体将DOCKER重新删除后安装，发现又可以跳转了；但是出现了一个新的问题，无法保存代理节点，一直提示500错误，哎，有点难啊讲真的；有没有联系方式可以私聊下我，感激不尽

**Comment by LQY96** [comment]
在数据库找找问题
