### ISSUE TITLE
关于如何换端口部署，

### ISSUE THREAD

**Issue by OSNewbie** [Ehco1996/django-sspanel#750]
我想问一下，如何用docker的方式换端口部署，因为默认80零端口和8080端口，已被占用，是否能提供其他端口的部署方式？

**Comment by Ehco1996** [comment]
可以的 修改 docker 的端口映射就可以

**Comment by OSNewbie** [comment]
> 可以修改docker的端口映射就可以了
两边端口是否能一致或者是不同，我指的是容器端口或者是访问那个端口
