### ISSUE TITLE
请求：添加等级有效期排序

### ISSUE THREAD

**Issue by LQY96** [Ehco1996/django-sspanel#753]
- 后台数据 - 用户 
 - [加入日期] - [等级有效期] - sub_link
 - 请求：在加入日期 右边 添加一个 等级有效期 排序 

 - 【求助】：有自己尝试修改admin.py,介于自己的djianggo语言太烂,更改后体验了无数次Bug 500 之后决定找大佬求助 : ( 
 - 就是在这里困扰的N+次 500
 - class UserAdmin(admin.ModelAdmin):
    list_display = [
        "username",
        "id",
        "level",
        "balance",
        "used_percentage",
        "date_joined",
        "sub_link",
    ]
 - 抱拳求助大佬添加这个功能

**Comment by Ehco1996** [comment]
@LQY96  可以尝试提个 pr， 在这里的数组里添加 等级有效期的字段就行
https://github.com/Ehco1996/django-sspanel/blob/95189acf9503739ef828e4cd440c05a921316227/apps/sspanel/admin.py#L14

代码改动就一行
<img width="471" alt="Screenshot 2022-11-26 at 10 26 45" src="https://user-images.githubusercontent.com/24697284/204068890-79f6c7df-1365-4ee3-8ad6-89d879a3daed.png">

**Comment by LQY96** [comment]
> @LQY96 可以尝试提交一个pr，在这里的数字里添加等级有效的字段就可以了
> 
> https://github.com/Ehco1996/django-sspanel/blob/95189acf9503739ef828e4cd440c05a921316227/apps/sspanel/admin.py#L14
> 
> 代号修改就一行 <img alt="屏幕截图 2022-11-26 在 10 26 45" width="471" src="https://user-images.githubusercontent.com/24697284/204068890-79f6c7df-1365-4ee3-8ad6-89d879a3daed.png">

谢谢大佬，我研究一下
