### ISSUE TITLE
在/admin绑定ss用户后仍然500错误

### ISSUE THREAD

**Issue by Code2qing** [Ehco1996/django-sspanel#78]
已经绑定了ss用户，点击账户信息、节点信息等500，并且当我尝试重新注册一个新用户，注册完毕后命令行显示该用户未绑定
![q -20180201044250](https://user-images.githubusercontent.com/23296014/35646496-5d403668-070a-11e8-81a8-4f52232566b6.png)
 ss user。
![q -20180201043546](https://user-images.githubusercontent.com/23296014/35646403-16ada0d2-070a-11e8-81c5-18191956de31.png)
![q -20180201044022](https://user-images.githubusercontent.com/23296014/35646424-2ac36142-070a-11e8-99f3-7cc162a0d0e7.png)

**Comment by Ehco1996** [comment]
建立数据库的时候 要把格式设置成utf8mb4

**Comment by Code2qing** [comment]
感谢，已经弄好，还有一个疑问就是不支持每个用户单独设置协议插件和混淆插件吗，启动的时候只会以user-config.json文件设置好的协议、混淆参数为准，即使在面板中更改协议插件，但实际上后端程序并没有改变。

**Comment by Ehco1996** [comment]
用户可以自定义各种设置
在用户面板里的**节点编辑界面**

但是要确保后台节点的自定义加密是打开的

**Comment by Code2qing** [comment]
已解决，修改`userapiconfig.py`中`API_INTERFACE`参数为`legendsockssr`可正常从面板同步协议、混淆参数，此前是按照Wiki中将`API_INTERFACE`设置为`ehcomod`。
