### ISSUE TITLE
更换主题好像有点问题

### ISSUE THREAD

**Issue by yigehaobb** [Ehco1996/django-sspanel#79]
更换主题后 打开很慢……default的秒开

**Comment by arrayJY** [comment]
八成是你自己的问题，我把所有主题都试了一遍，几乎全部都在1s内完成相应。
你最好用开发者工具->网络看看哪个文件接收的最慢。

**Comment by HelicalH** [comment]
因为其他主题用了 fonts.googleapis.com 的字体，国内被墙了。
