### ISSUE TITLE
release on Feb  2, 2022 version  images bug 

### ISSUE THREAD

**Issue by xiaxichen** [Ehco1996/django-sspanel#799]
**问题的描述
关于 django-sspanel latest 版本 code 中使用的 ehco1996/django-sspanel:runtime image 在运行中会报错 mysql 驱动没有找到
**项目的配置文件**
`#--->服务端口 nginx
port=80

#--->mysql
#mysql数据库设置 db.py
MYSQL_USER=root
MYSQL_PASSWORD=*
# mysql服务设置
# mysql host默认请保持注释*
# MYSQL_HOST=mysql
# mysql服务密码设置
MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
#设置MYSQL_PASSWORD即可

#--->网站定制 sites.py
# 网站域名设置（请正确填写，不然订阅功能会失效：
HOST=http://*:8000
# 网站密钥
SECRET_KEY=*
# 是否开启注册
ALLOW_REGISTER=True
# 默认的theme
# 可选列表在 apps/constants.py 里的THEME_CHOICES里
DEFAULT_THEME=default
# 默认加密混淆协议
DEFAULT_METHOD=aes-256-cfb
# 签到流量设置
MIN_CHECKIN_TRAFFIC=10485760
# 10 * 1024 * 1024 (10MB)
MAX_CHECKIN_TRAFFIC=209715200
# 200 * 1024 * 1024 (200MB)
# 网站title
TITLE=*
SUBTITLE=*
# 用户邀请返利比例
INVITE_PERCENT=0.2
# 用户能生成的邀请码数量
INVITE_NUM=5
# 网站邀请页提示语
INVITEINFO=邀请码实时更新，如果用完了就没了
# 部分API接口TOKEN
TOKEN=*
# SHORT_URL_ALPHABET 请随机生成,且不要重复
DEFAULT_ALPHABET=ebzgrqoltisvfajxwdcyhpnkmu
# FOR SIMPLE UI
SIMPLEUI_HOME_INFO=False
SIMPLEUI_DEFAULT_ICON=False
# 是否开启用户到期邮件通知
EXPIRE_EMAIL_NOTICE=False

#--->邮箱设置 email.py
# 是否开启邮件功能
USE_SMTP=True
EMAIL_USE_SSL=True
EMAIL_HOST=smtp.163.com
EMAIL_PORT=465
EMAIL_HOST_USER=user
EMAIL_HOST_PASSWORD=yourpass
DEFAULT_FROM_EMAIL=user
#可以与EMAIL_HOST_USER一致
# FOR mailgun*
# MAILGUN_API_KEY=key
# MAILGUN_SENDER_DOMAIN=domain

#--->支付宝对接 pay.py*
#USE_ALIPAY=False
#CHECK_PAY_REQ_IP_FROM_CN=False
#ALIPAY_APP_ID=XXXXXXXX
#ALIPAY_APP_PRIVATE_KEY_STRING="-----BEGIN RSA PRIVATE KEY-----
#-----END RSA PRIVATE KEY-----"
#ALIPAY_PUBLIC_KEY_STRING="-----BEGIN PUBLIC KEY-----
#-----END PUBLIC KEY-----"
ALIPAY_TRADE_INFO="{}元充值码"

#--->其他*
# 时区
TZ=Asia/Shanghai
# msyql host
#MYSQL_HOST=mysql
# redis host
#REDIS_HOST=redis
# production不开启debug，development开启debug
DJANGO_ENV=production
#DJANGO_ENV=development`
**如何复现**
正常下载 [Source code
(tar.gz)](https://github.com/Ehco1996/django-sspanel/archive/refs/tags/v2022.2.2.tar.gz) 这个code 然后启动 django 日志就会报错
django.core.exceptions.ImproperlyConfigured: Error loading MySQLdb module.
Did you install mysqlclient?
**相关截图/log**
![image](https://user-images.githubusercontent.com/34499404/223086715-5adc8f02-3c25-4375-9202-50c00273059a.png)
**其他信息**

**Comment by Ehco1996** [comment]
runtime ci broken...
see the error log
```
ERROR: libressl-dev-3.6.2-r0: trying to overwrite usr/lib/libcrypto.so owned by openssl-dev-3.0.8-r0.
ERROR: libressl-dev-3.6.2-r0: trying to overwrite usr/lib/libssl.so owned by openssl-dev-3.0.8-r0.
ERROR: libressl-dev-3.6.2-r0: trying to overwrite usr/lib/pkgconfig/libcrypto.pc owned by openssl-dev-3.0.8-r0.
ERROR: libressl-dev-3.6.2-r0: trying to overwrite usr/lib/pkgconfig/libssl.pc owned by openssl-dev-3.0.8-r0.
ERROR: libressl-dev-3.6.2-r0: trying to overwrite usr/lib/pkgconfig/openssl.pc owned by openssl-dev-3.0.8-r0.
```

dose anyone familiar with this error?

**Comment by xiaxichen** [comment]
我尝试使用 poetry install 构建这个环境 获得了已下的错误 
系统 ubuntu 22.04 tls
Cpu amd X86 64
<img width="1658" alt="image" src="https://user-images.githubusercontent.com/34499404/223101903-b2b59940-fc70-44d9-8d7a-4f62571ad8c7.png">

**Comment by xiaxichen** [comment]
> runtime ci broken... see the error log
> 
> ```
> ERROR: libressl-dev-3.6.2-r0: trying to overwrite usr/lib/libcrypto.so owned by openssl-dev-3.0.8-r0.
> ERROR: libressl-dev-3.6.2-r0: trying to overwrite usr/lib/libssl.so owned by openssl-dev-3.0.8-r0.
> ERROR: libressl-dev-3.6.2-r0: trying to overwrite usr/lib/pkgconfig/libcrypto.pc owned by openssl-dev-3.0.8-r0.
> ERROR: libressl-dev-3.6.2-r0: trying to overwrite usr/lib/pkgconfig/libssl.pc owned by openssl-dev-3.0.8-r0.
> ERROR: libressl-dev-3.6.2-r0: trying to overwrite usr/lib/pkgconfig/openssl.pc owned by openssl-dev-3.0.8-r0.
> ```
> 
> dose anyone familiar with this error?

能发给我已下这个镜像的build命令嘛？

**Comment by xiaxichen** [comment]
我找到了这个Dockerfile 重新build后成功了。
