### ISSUE TITLE
SS连接问题

### ISSUE THREAD

**Issue by SZ98** [Ehco1996/django-sspanel#81]
无论是什么端口和密码都可以登上PC端SS, 但是安卓端怎么改设置登上都没网(连接另外一个服务器的ss可以用),,,请问这是哪里出问题了?????????

**Comment by Ehco1996** [comment]
应该死安卓端的客户端问题

**Comment by SZ98** [comment]
那无论是什么端口和密码都可以登上PC端SS,是什么原因。。

**Comment by arrayJY** [comment]
你可以在安卓客户端上新建一个连接试试，信息照样填写。
我之前就是这样弄好的，改默认连接的数据，数据无误也连不上（摊手），新建一个重新填写就好了。
