### ISSUE TITLE
登录问题

### ISSUE THREAD

**Issue by iRKing** [Ehco1996/django-sspanel#82]
登录账户和注册账户时，会出现Server 500错误，是哪里设置错了吗

**Comment by Ehco1996** [comment]
参考[如何正确debug](https://github.com/Ehco1996/django-sspanel/wiki/%E5%A6%82%E4%BD%95%E6%AD%A3%E7%A1%AE%E7%9A%84debug)

自己解决不了
可以把log发上来

**Comment by iRKing** [comment]
![llukr0x6cl m5km 05w](https://user-images.githubusercontent.com/13493079/36237775-02b6d726-1239-11e8-8323-3529bb88f4e7.png)

错误是这样的  您能看看是怎么回事吗(

**Comment by Ehco1996** [comment]
admin账户需要自己去后台添加一下端口，可以参考wiki的对应部分

**Comment by iRKing** [comment]
还是不行，谢谢啦，新年快乐~
