### ISSUE TITLE
请勿如何针对用户或节点限速

### ISSUE THREAD

**Issue by jiangzhihui8** [Ehco1996/django-sspanel#85]
sspanel魔改可以有对用户/节点限速的设置，请问大大此面板如何限速？如何保证用户不被其他用户占用带宽过大所影响

**Comment by Ehco1996** [comment]
在后端的里的 user-config.json文件里限制

以后会将这个选项加入面板里

**Comment by cheapssr** [comment]
嗯嗯，这个我也觉得很好，不如一步到位，比如：设置限速2m带宽，也就是200kb/s，用户或者端口，20分钟时间都跑满速，自动停掉端口10分钟。。10分钟之后自动打开。。这样省的在游戏节点乱跑。
