### ISSUE TITLE
开发时怎样应用 .env 文件

### ISSUE THREAD

**Issue by neilbowman666** [Ehco1996/django-sspanel#862]
**问题的描述**
复制模板并生成 .env 文件
在 `poetry shell` 下使用 `python manage.py migrate` 命令，无法连接数据库，没有按照 .env 文件连接数据库。

**项目的配置文件**
.env

**如何复现**
同问题描述

**相关截图/log**
![image](https://github.com/Ehco1996/django-sspanel/assets/16320758/ba0530ba-58a0-48e1-9a09-608a45fc63d1)

**其他信息**
无

**Comment by Ehco1996** [comment]
这不是 bug .env 文件是给 docker compose 用的，可以搜搜相关的文档，

**Comment by neilbowman666** [comment]
可以使用 python-dotenv 来让 .env 在本机开发环境生效吗？我将合并进入 dev 分支。

**Comment by Ehco1996** [comment]
> 可以使用 python-dotenv 来让 .env 在本机开发环境生效吗？我将合并进入 dev 分支。

lgtm

**Comment by Ehco1996** [comment]
closed due to stale
