### ISSUE TITLE
邮件配置

### ISSUE THREAD

**Issue by xchensir** [Ehco1996/django-sspanel#87]
邮件配置能在百忙之中出个教程吗？不是很懂，查了好多资料还是没搞明白
该面板支持，账号临近到期、流量不够会自动发邮件提醒的功能嘛？
清理僵尸粉的功能，能再发一下链接地址嘛，之前在telgram里看到过一次，没记住

**Comment by Ehco1996** [comment]
邮件功能只能拿来找回密码

清理僵尸用户，我下个版本做成按钮 放在后台里吧
