### ISSUE TITLE
简单部署

### ISSUE THREAD

**Issue by jxyk2007** [Ehco1996/django-sspanel#888]
1.phpstudy 安装一个mysql 创建数据库djangosspanel
2.修改db.py文件

![image](https://github.com/Ehco1996/django-sspanel/assets/44092526/b9d83a65-f4cb-4e5f-ad4a-b21147263a0b)
3.配置.env
![image](https://github.com/Ehco1996/django-sspanel/assets/44092526/ace0e335-25bc-4bd8-8280-66bb904ac38e)
4.安装python
![image](https://github.com/Ehco1996/django-sspanel/assets/44092526/a8bf98f1-0927-4c42-b344-24968f902de4)
5.克隆git clone https://github.com/Ehco1996/django-sspanel.git
 
![image](https://github.com/Ehco1996/django-sspanel/assets/44092526/a10da926-1b0a-41b0-bb50-ee25d8af1756)
6.导入数据库python manage.py migrate
![image](https://github.com/Ehco1996/django-sspanel/assets/44092526/41a01096-f231-426b-88b4-310d1cbc5ce0)
7.创建管理员信息python manage.py create_admin --email "admin@qq.com" --username "admin" --password "admin"
![image](https://github.com/Ehco1996/django-sspanel/assets/44092526/ecd3f0ba-af89-4d2b-8450-83f86ce66171)
8.安装各种模块，根据提示去pip install 
9.运行服务python manage.py runserver

![image](https://github.com/Ehco1996/django-sspanel/assets/44092526/0690fc58-62bd-4601-946b-508fe98a41b7)

**Comment by jxyk2007** [comment]
bug 后台创建用户，输入的密码未加密就写入到数据库，登录时前端会把密码加密比对数据库的密码，不一致无法登录。
弃

**Comment by Ehco1996** [comment]
欢迎将文档提到 doc 分支里形成文档 🙏

另外当前的确不支持在后台直接创建用户，并不是 bug 哦

**Comment by jxyk2007** [comment]
> 欢迎将文档提到 doc 分支里形成文档 🙏
> 
> 另外当前的确不支持在后台直接创建用户，并不是 bug 哦

管理员就无法修改用户的密码了

**Comment by Ehco1996** [comment]
> > 欢迎将文档提到 doc 分支里形成文档 🙏
> > 另外当前的确不支持在后台直接创建用户，并不是 bug 哦
> 
> 管理员就无法修改用户的密码了

你这样说的确, 欢迎提供 pr

**Comment by Ehco1996** [comment]
我仔细想了一下,按照现在的 py 生态来看, docker 就是最简单的部署方式, 所以这个 issue 暂时关闭了
