### ISSUE TITLE
这几个在哪小白不知道哪里找到安装python3-devel

### ISSUE THREAD

**Issue by 925001777** [Ehco1996/django-sspanel#9]
$ sudo yum install python3-devel
    $ pip3 install mysqlclient
    
    # 最后安装其他第三方包
    $ pip install -r requirements.txt

**Comment by 925001777** [comment]
如果觉得复杂，可以使用一件脚本

$ curl -L https://raw.githubusercontent.com/pyenv/pyenv-installer/master/bin/pyenv-installer | bash

————————————————————————————
1 在你想要安装PYENV的目录

 $ git clone https://github.com/pyenv/pyenv.git ~/.pyenv
----------------------问一件脚本装完后 下面 这些还需要操作吗？不懂这个程序是干啥的路过

**Comment by Ehco1996** [comment]
@925001777 
pyenv是一个管理Python版本的工具
执行一件安装脚本之后，就不需要下面的步骤了

**Comment by 925001777** [comment]
用了一键脚本后面好像是到了
$ pip3 install mysqlclient
    
    # 最后安装其他第三方包
    $ pip install -r requirements.txt 
这两部就不行了 已经放弃了 改用其他脚本了
