### ISSUE TITLE
商品问题

### ISSUE THREAD

**Issue by number018** [Ehco1996/django-sspanel#90]
当前为在账号原有等级到期时间的基础上增加商品购买的时间。比如我账号到期时间为2018年3：10，今天是3：9，我买了一个30天无限流量的商品，就应该更新为2018年4：9或者  加30天来计算。而不是在原有基础上直接增加，变成4：10。假设有一个1元1G测试的商品。我买一个30天的，快到期时买一个测试的，就直接又加了一天无限的使用时间。这是不合逻辑的。

**Comment by Ehco1996** [comment]
不知道你在说什么
先把你说话的逻辑理一理再说吧.....
