### ISSUE TITLE
请问怎样配置单端口多用户模式？

### ISSUE THREAD

**Issue by jfc234** [Ehco1996/django-sspanel#91]
请问怎样配置单端口多用户模式？

**Comment by zhkufish** [comment]
同问

**Comment by cheapssr** [comment]
顶起

**Comment by hyjsostop** [comment]
前端就节点哪里就协议选择auth_aes128_md5或auth_aes128_sha1注意下。
后端主要是要配置user-config.json这个文件。当然userapiconfig.py这个文件与多端口的配置是一样的。
修改这一部分与前端一样
"additional_ports": {
        "你使用的端口": {
            "passwd": "你前端设置的单端口密码",
            "method": "你采用的加密",
            "protocol": "你使用的协议",
            "protocol_param": "#",
            "obfs": "你采用的混淆",
            "obfs_param": ""
