### ISSUE TITLE
有一个请求不知道是什么 找不到，404

### ISSUE THREAD

**Issue by wangxingsheng** [Ehco1996/django-sspanel#925]
**问题的描述**
有一个请求不知道是什么 找不到，404
**项目的配置文件**

**如何复现**

**相关截图/log**
![image](https://github.com/Ehco1996/django-sspanel/assets/39944221/407c67d4-6098-436a-8ebe-1edbe14ea3f0)

**其他信息**

**Comment by Ehco1996** [comment]
这是你浏览器发出的请求，可是看一下 console 里有没有更多内容
并不是 bug，请不要随意贴 label
